var i18n = (
    {
        s000: 'English language by bublikOff <span style="color:#FFA500">xplay@itkey.ru</span>',
        s001: 'Restart',
        s002: 'Email for support and feedback <span style="color:#FFA500">xplay@itkey.ru</span> or visit forum <span style="color:#FFA500">http://xplay.itkey.ru/forum/</span>',
        s003: 'To sign in, visit <span style="color:#FFA500">https://plex.tv/link</span> and enter the code above.',
        s004: 'Retry account linking',
        s005: 'The list of available servers for {0}',
        s006: 'No available Plex Media Servers',
        s007: 'Cancel',
        s008: 'Unlink {0}',
        s009: 'Enter your Plex account PIN code',
        s010: 'Continue watching',
        s011: 'Recently Added',
        s012: 'Nothing to display on dashboard',
        s013: 'Test period expired',
        s014: 'You have {0} offline starts left. Please connect your TV to the Internet.',
        s015: 'You must connect your TV to the Internet to restore activation status',
        s016: 'Episode {0}',
        s017: 'Season {0}',
        s018: 'Unwatched',
        s019: '{0} Parts',
        s020: 'Director',
        s021: 'Writer',
        s022: 'Cast',
        s023: 'Video',
        s024: 'Audio',
        s025: 'Subtitles',
        s026: 'None',

        // -- Library (section) --

        s027: 'filtered',
        s028: ' of ',
        s029: 'Empty library',
        s030: 'No matches were found',

        // -- Filters dialog --

        s031: 'Filters',
        s032: 'Show unwatched only',
        s033: 'Reset',
        s034: 'Apply',

        // -- Settings dialog --

        s035: 'General',
        s036: 'Video player',
        s037: 'Music player',
        s038: 'Photo viewer',
        s039: 'Controls',
        s040: 'Home users',
        s041: 'Account',
        s042: 'About',
        s043: 'Common',
        s044: 'Interface language',
        s045: 'Unknown',
        s046: 'Clock format',
        s047: 'Continue watching',
        s048: 'Audio theme',
        s049: 'No',
        s050: 'Yes',
        s051: 'Loop',
        s052: 'Screensaver',
        s053: 'Disabled',
        s054: 'Media rating',
        s055: 'Stars',
        s056: 'Number',
        s057: 'Media posters',
        s058: 'Posters quality',
        s059: 'Main media poster quality',
        s060: 'Media arts',
        s061: 'Show',
        s062: 'Show media art',
        s063: 'Quality',
        s064: 'Media art quality',
        s065: 'Opacity',
        s066: 'Media art opacity',
        s067: 'Blur effect',
        s068: 'Media art blur effect',
        s069: 'Playback',
        s070: 'Playback mode',
        s071: 'Auto play next episode',

        // Auto play next episode
        s072: 'Ask',

        s073: 'Controls wake up',
        s074: 'Cursor move',
        s075: 'Button press',
        s076: 'Cursor or button',
        s077: 'Cinema Trailers',
        s078: 'Seek interval',
        s079: 'Controls timeout',
        s080: 'Transcoding',
        s081: 'Quality',
        s082: 'Transcoding quality',
        s083: 'Original',
        s084: 'Audio boost',
        s085: 'Transcoding audio boost',
        s086: 'Small',
        s087: 'Large',
        s088: 'Huge',
        s089: 'Protocol',
        s090: 'Transcoding streaming protocol',
        s091: 'Direct play',
        s092: 'False',
        s093: 'True',
        s094: 'Direct stream',
        s095: 'Size',
        s096: 'Subtitles size',
        s097: 'Tiny',
        s098: 'Small',
        s099: 'Normal',
        s100: 'Big',
        s101: 'Huge',
        s102: 'Codepage (external)',
        s103: 'Subtitles codepage (external only)',
        s104: 'Position (external)',
        s105: 'Subtitles position (external only)',
        s106: 'Color (external)',
        s107: 'Subtitles color (external only)',
        s108: 'White',
        s109: 'Silver',
        s110: 'Gray',
        s111: 'Black',
        s112: 'Purple',
        s113: 'Red',
        s114: 'Orange',
        s115: 'Yellow',
        s116: 'Green',
        s117: 'Lime',
        s118: 'Blue',
        s119: 'Light blue',
        s120: 'Queue (folder view)',
        s121: 'Queue type (folder view)',
        s122: 'Native',
        s123: 'Local',
        s124: 'Format',
        s125: 'Transcoding format',
        s126: 'Bitrate',
        s127: 'Transcoding bitrate',
        s128: 'Autostart playback',
        s129: 'Playback timeout',
        s130: 'Loopback playback',
        s131: 'Show color background',
        s132: 'Photo display quality',
        s133: 'Previous',
        s134: 'Next',
        s135: 'Play/Pause',
        s136: 'Stop',
        s137: 'Rewind',
        s138: 'Forward',
        s139: 'Fast Rewind',
        s140: 'Fast Forward',
        s141: 'Red Button',
        s142: 'Green Button',
        s143: 'Blue Button',
        s144: 'Yellow Button',
        s145: 'Home users',
        s146: 'Remove',
        s147: 'Only two users can be used as local home users.<br>In case you want more home users please use native Plex Home Users feature.',
        s148: 'Here you can set up a group of users that all use Plex together.<br/>For instance, there might be a family of users (parents and children) that all<br/>use Plex on TV connected to the same Plex Media Server in their house.',
        s149: 'Connecting to Plex services ...',
        s150: 'To link a Plex account as a local home user<br/>visit <span style="color:#FFA500">https://plex.tv/link</span> and enter the code above.',
        s151: 'Add a local home user',
        s152: 'Signed in as',
        s153: 'User ID',
        s154: 'Activation status',
        s155: 'UNKNOWN',
        s156: 'Unlink Plex account',
        s157: 'This version of application has a limited period of usage.<br/>To remove limitation, please visit our website <span style="color:#FFA500">https://xplay.itkey.ru</span><br>and don\'t forget your user ID.',
        s158: 'An unofficial client for Plex Media Server.',
        s159: 'Logos, trademarks and other registered trademarks belong to their respective owners.<br>All rights reserved.',
        s160: 'Reset to default',

        // -- ... --

        s161: 'Toggling media watch status ...',
        s162: 'You must connect your TV to the Internet to restore activation status <br/> and remove playback restriction',
        s163: 'You must connect your TV to the Internet to remove playback restriction',
        s164: 'This version of application has a limited period of usage. <br/> You can\'t play any media files anymore.',
        s165: 'Creating playback queue ...',
        s166: 'Unknown genre',
        s167: 'Aw, Snap! Something went wrong',
        s168: 'Unable to use selected user. <br/> Failed to communicate with Plex API.',
        s169: 'An incorrect PIN code',
        s170: 'Requesting user information ...',
        s171: 'An incorrect PIN code. <br/> Repeated attempts may temporarily disable sign in',
        s172: 'Unable to process user information<br/>Failed to communicate with Plex API',
        s173: 'Trying to connect to {0} ...',
        s174: 'Aw, Snap! Something went wrong and we were unable to connect to {0}',
        s175: 'Successfully connected to {0}',
        s176: 'Connecting to {0} ...',
        s177: 'Aw, Snap! Something went wrong and authentication to {0} failed',
        s178: 'Aw, Snap! Something went wrong and communication with {0} failed',
        s179: 'Unable to retrieve server list from Plex API',
        s180: 'Failed to communicate with Plex API',
        s181: 'Requesting account information ...',
        s182: 'Connecting to plex.tv ...',
        s183: 'Requesting dashboard information ...',
        s184: 'Aw, Snap! Something went wrong and we were unable to process server response',
        s185: 'Home',
        s186: 'Continue watching',
        s187: 'Recently added',
        s188: 'Resume from {0}',
        s189: 'Start from beginning',
        s190: 'Resume playback',
        s191: 'Trailers',
        s192: 'Audio tracks',
        s193: 'Subtitles',
        s194: 'More actions',
        s195: 'Are you sure you want to delete this item from your filesystem?',
        s196: 'Delete',
        s197: 'Deleting media item from filesystem ...',
        s198: 'Requesting media details ...',
        s199: 'Trailer',
        s200: 'Media',
        s201: 'Transcode',
        s202: 'Loading media poster ...',
        s203: 'Loading media art ...',
        s204: 'Aw, Snap! Something went wrong and we were unable to retrieve media details',
        s205: 'Sorting',
        s206: '14 posters',
        s207: '33 posters',
        s208: '27 posters (without titles)',
        s209: '48 posters (without titles)',
        s210: 'Grid size',
        s211: 'By Type',
        s212: 'By Artists',
        s213: 'By Movies',
        s214: 'By TV Shows',
        s215: 'View mode',
        s216: 'By Folders',
        s217: 'Creating playback queue ...',
        s218: 'Requesting library items ...',
        s219: 'Aw, Snap! Something went wrong while communicating with {0}',
        s220: 'Requesting library items ...',
        s221: 'Refresh',
        s222: 'View grid size',
        s223: 'Restarting playback queue ...',
        s224: 'Play next episode?',
        s225: 'Play',
        s226: 'Aw, Snap! Something went wrong and we were unable to toggle media watch status',
        s227: 'You aborted the video playback',
        s228: 'A network error caused the video download to fail part-way',
        s229: 'The video playback was aborted due to a corruption problem or because the video used features your browser did not support',
        s230: 'The video could not be loaded, either because the server or network failed or because the format is not supported',
        s231: 'An unknown error occurred (undefined code)',
        s232: 'An unknown error occurred',
        s233: 'Demo period expires in {0} day(s)',
        s234: 'Demo period expires in {0}',
        s235: 'S{0}',
        s236: 'E{0}',
        s237: 'Settings',

        // Auto play next episode
        s238: 'Yes',

        //
        s239: 'Search in {0}',
        s240: 'h [h] mm [min]',
        s241: 'mm [min] ss [sec]',
        s242: 'mm [min]',
        s243: 'ss [sec]'
    });