var i18n = (
    {
        s000: 'Traducción al Español por LFLR <span style="color:#FFA500">lflr@my-hdd.com</span>',
        s001: 'Reiniciar',
        s002: 'Correo electrónico de soporte y feedback <span style="color:#FFA500">xplay@itkey.ru</span> o visita el foro <span style="color:#FFA500">http://xplay.itkey.ru/forum/</span>',
        s003: 'Para iniciar sesión, visita <span style="color:#FFA500">https://plex.tv/link</span> y escribe el codigo que aparecerá.',
        s004: 'Volver a intentar la unión con la cuenta',
        s005: 'The list of available servers for {0}',
        s006: 'Plex Media Servers no disponible',
        s007: 'Cancelar',
        s008: 'Desconectar {0}',
        s009: 'Escribe el codigo PIN de tu cuenta PLEX',
        s010: 'Seguir viendo',
        s011: 'Recientemente añadido',
        s012: 'Nada que mostrar en el tablero',
        s013: 'El período de prueba ha finalizado',
        s014: 'Tienes {0} inicios offline restantes. Porfavor conecta la TV a internet.',
        s015: 'Debes conectar tu TV a Internet para restablecer el estado de activación',
        s016: 'Episodio {0}',
        s017: 'Temporada {0}',
        s018: 'No visto',
        s019: '{0} Partes',
        s020: 'Director',
        s021: 'Guionista',
        s022: 'Reparto',
        s023: 'Video',
        s024: 'Audio',
        s025: 'Subtítulos',
        s026: 'Ninguno',

        // -- Biblioteca (sección) --

        s027: 'filtered',
        s028: ' of ',
        s029: 'Biblioteca vacía',
        s030: 'No se encontraron resultados',

        // -- Diálogo de filtros --

        s031: 'Filtros',
        s032: 'Moatrar únicamente los no vistos',
        s033: 'Reiniciar',
        s034: 'Aplicar',

        // -- Diálogo de configuración --

        s035: 'General',
        s036: 'Reproductor de vídeo',
        s037: 'Reproductor de música',
        s038: 'Galería de fotos',
        s039: 'Controles',
        s040: 'Usuarios locales',
        s041: 'Cuenta',
        s042: 'Acerca de',
        s043: 'Common',
        s044: 'Lenguaje de la interfaz',
        s045: 'Desconocido',
        s046: 'Formato del reloj',
        s047: 'Seguir viendo',
        s048: 'Tema de audio',
        s049: 'No',
        s050: 'sí',
        s051: 'Bucle',
        s052: 'Salvapantallas',
        s053: 'Desactivado',
        s054: 'Clasificación de medios',
        s055: 'Estrellas',
        s056: 'Número',
        s057: 'Media posters',
        s058: 'Calidad de los posters',
        s059: 'Calidad pósters del media art',
        s060: 'Media arts',
        s061: 'Mostrar',
        s062: 'Mostrar media art',
        s063: 'Calidad',
        s064: 'Calidad media art',
        s065: 'Opacidad',
        s066: 'Opacidad media art',
        s067: 'Efecto Blur',
        s068: 'Efecto Blur del media art',
        s069: 'Reproducción',
        s070: 'Modo de reproducción',
        s071: 'Auto-reproducir capítulos',

        // Auto play next episode
        s072: 'Preguntar',

        s073: 'Despertar controles',
        s074: 'Mover cursor',
        s075: 'Pulsar botón',
        s076: 'Cursor o botón',
        s077: 'Tráilers del cine',
        s078: 'Intervalo de búsqueda',
        s079: 'Tiempo de espera controles',
        s080: 'Transcodificación',
        s081: 'Calidad',
        s082: 'Calidad de transcodificación',
        s083: 'Original',
        s084: 'Aumento de audio',
        s085: 'Aumento audio de transcodificación',
        s086: 'Pequeño',
        s087: 'Grande',
        s088: 'Muy grande',
        s089: 'Protocolo',
        s090: 'Protocolo del streaming de transcodificación',
        s091: 'Direct play',
        s092: 'Falso',
        s093: 'Verdadero',
        s094: 'Stream directo',
        s095: 'Tamaño',
        s096: 'Tamaño subtítulos',
        s097: 'Muy pequeño',
        s098: 'Pequeño',
        s099: 'Normal',
        s100: 'Grande',
        s101: 'Muy Grande',
        s102: 'Página de códigos (externa)',
        s103: 'Página de códigos de subtítulos (solo externo)',
        s104: 'Posición (externo)',
        s105: 'Posición de subtítulos (solo externo)',
        s106: 'Color (externo)',
        s107: 'Color de subtítulos (solo externo)',
        s108: 'Blanco',
        s109: 'Plateado',
        s110: 'Gris',
        s111: 'Negro',
        s112: 'Lila',
        s113: 'Rojo',
        s114: 'Naranja',
        s115: 'Amarillo',
        s116: 'Verde',
        s117: 'Lima',
        s118: 'Azul',
        s119: 'Azul claro',
        s120: 'Cola (vista de carpeta)',
        s121: 'Tipo de cola (vista de carpeta)',
        s122: 'Nativo',
        s123: 'Local',
        s124: 'Formato',
        s125: 'Formato de transcodificación',
        s126: 'Bitrate',
        s127: 'Bitrate de transcodificación',
        s128: 'Inicio automático',
        s129: 'Tiempo de espera',
        s130: 'Reproducción en bucle',
        s131: 'Mostrar color de fondo',
        s132: 'Calidad fotografías',
        s133: 'Anterior',
        s134: 'Siguiente',
        s135: 'Play/Pausa',
        s136: 'Stop',
        s137: 'Rebobinar',
        s138: 'Adelante',
        s139: 'Rebobinado rápido',
        s140: 'Avance rápido',
        s141: 'Botón rojo',
        s142: 'Botón verde',
        s143: 'Botón azul',
        s144: 'Botón amarillo',
        s145: 'Usuarios Locales',
        s146: 'Borrar',
        s147: 'Solo se pueden usar dos usuarios como usuarios del hogar locales. <br> En caso de que desee más usuarios del hogar, use la función nativa de usuarios de Plex Home..',
        s148: 'Aquí puede configurar un grupo de usuarios si usan Plex juntos. <br/> Por ejemplo, en el caso de una familia de usuarios (padres e hijos) que <br/> usen Plex en un televisor conectado al mismo Plex Media Server en su casa. ',
        s149: 'Conectando a los servicios de Plex ...',
        s150: 'Para vincular una cuenta Plex como un usuario del hogar local<br/>visite <span style="color:#FFA500">https://plex.tv/link</span> e ingrese el código de arriba.',
        s151: 'Agrega un usuario local',
        s152: 'Registrado como',
        s153: 'ID del usuaro',
        s154: 'Estado de activación',
        s155: 'DESCONOCIDO',
        s156: 'Desvincular la cuenta de Plex',
        s157: 'Esta versión de la aplicación tiene un período de uso limitado.<br/>Para eliminar la limitación, visite nuestra página web <span style="color:#FFA500">https://xplay.itkey.ru</span><br>y no olvide su ID de usuario.',
        s158: 'Un cliente no oficial para Plex Media Server.',
        s159: 'Los logotipos, las marcas comerciales y otras marcas registradas pertenecen a sus respectivos propietarios. <br> Todos los derechos reservados.',
        s160: 'Restablecer predeterminados',

        // -- ... --

        s161: 'Alternar el estado del reloj de medios ...',
        s162: 'Debes conectar tu TV a Internet para restablecer el estado de activación <br/> y eliminar la restricción de reproducción',
        s163: 'Debes conectar tu TV a Internet para eliminar la restricción de reproducción',
        s164: 'Esta versión de la app tiene un período de uso limitado. <br/> Ya no puedes reproducir ningún archivo multimedia.',
        s165: 'Crear cola de reproducción ...',
        s166: 'Género desconocido',
        s167: 'Oh, No! Algo salió mal',
        s168: 'No se puede usar el usuario seleccionado. <br/> Error al comunicarse con la API de Plex.',
        s169: 'Código PIN incorrecto',
        s170: 'Solicitando información del usuario ...',
        s171: 'Código PIN incorrecto. <br/> Varios intentos pueden inhabilitar temporalmente el inicio de sesión',
        s172: 'No se puede procesar la información del usuario<br/>Error al comunicarse con la API de Plex',
        s173: 'Intentando conectarse a {0} ...',
        s174: 'Oh, No! Algo salió mal y no pudimos conectarnos {0}',
        s175: 'Conectado con éxito a {0}',
        s176: 'Conectando a {0} ...',
        s177: 'Oh, No! Algo salió mal y la autentificación a {0} falló',
        s178: 'Oh, No! Algo salió mal y la comunicación con {0} falló',
        s179: 'No se puede recuperar la lista de servidores de la API de Plex',
        s180: 'Error al comunicarse con la API de Plex',
        s181: 'Solicitando información de cuenta ...',
        s182: 'Conectando a plex.tv ...',
        s183: 'Solicitando información del panel ...',
        s184: 'Oh, No! Algo salió mal y no pudimos procesar la respuesta del servidor',
        s185: 'Inicio',
        s186: 'Seguir viendo',
        s187: 'Recientemente añadido',
        s188: 'Resumir desde {0}',
        s189: 'Comenzar desde el principio',
        s190: 'Reanudar la reproducción',
        s191: 'Trailers',
        s192: 'Pistas de audio',
        s193: 'Subtítulos',
        s194: 'Mas acciones',
        s195: '¿Seguro que quieres eliminar este elemento de tu sistema de archivos?',
        s196: 'Borrar',
        s197: 'Eliminando elementos multimedia del sistema de archivos ...',
        s198: 'Solicitando detalles de los medios ...',
        s199: 'Trailer',
        s200: 'Media',
        s201: 'Transcodificar',
        s202: 'Cargando media poster ...',
        s203: 'Cargando media art ...',
        s204: 'Oh, No! Algo salió mal y no pudimos recuperar los detalles de los medios',
        s205: 'Clasificación',
        s206: '14 posters',
        s207: '33 posters',
        s208: '27 posters (without titles)',
        s209: '48 posters (without titles)',
        s210: 'Tamaño de la cuadrícula',
        s211: 'Por tipo',
        s212: 'Por artistas',
        s213: 'Por películas',
        s214: 'Por series',
        s215: 'Modo de vista',
        s216: 'Por carpetas',
        s217: 'Crear cola de reproducción ...',
        s218: 'Solicitar elementos de la biblioteca ...',
        s219: 'Oh, No! Algo salió mal al comunicarse con {0}',
        s220: 'Solicitando elementos de la biblioteca ...',
        s221: 'Refrescar',
        s222: 'Ver tamaño de cuadrícula',
        s223: 'Reiniciar la cola de reproducción ...',
        s224: 'Reproducir siguiente episodio?',
        s225: 'Reproducir',
        s226: 'Oh, No! Algo salió mal y no pudimos cambiar el estado de los medios',
        s227: 'Has abortado la reproducción del video',
        s228: 'Un error de red provocó que la descarga de video fallara parcialmente',
        s229: 'La reproducción del video se canceló debido a un problema o porque el video utilizó funciones que su navegador no admitía',
        s230: 'El video no pudo reproducirse, el servidor o la red fallaron o el formato no es compatible',
        s231: 'Un error desconocido ocurrió (undefined code)',
        s232: 'Un error desconocido ocurrió',
        s233: 'El período de prueba expira en {0} dia(s)',
        s234: 'El período de prueba expira en {0}',
        s235: 'O{0}',
        s236: 'P{0}',
        s237: 'Opciones',

        // Auto play next episode
        s238: 'sí'
    });