var i18n = (
    {
        s000: 'Eesti tõlge Argo "Six" Sieger<span style="color:#FFA500">six@six.ee</span>',
        s001: 'Taaskäivita',
        s002: 'Kasutajatoeks ja tagasiside andmiseks kirjutage <span style="color:#FFA500">xplay@itkey.ru</span> või külastage foorumit <span style="color:#FFA500">http://xplay.itkey.ru/forum/</span>',
        s003: 'Sisselogimiseks minge <span style="color:#FFA500">https://plex.tv/link</span> ja sisestage eeltoodud kood.',
        s004: 'Proovige uuesti konto sidumist',
        s005: 'Saadavate serverite loend {0}',
        s006: 'Plex Media servereid pole saadaval',
        s007: 'Tühista',
        s008: 'Eemalda {0}',
        s009: 'Sisesta Plex konto PIN-kood',
        s010: 'Pooleli',
        s011: 'Viimati lisatud',
        s012: 'Avaleht on tühi',
        s013: 'Testperiood on lõppenud',
        s014: 'Teil on jäänud {0} võrguühenduseta starti. Palun ühendage teler internetiga.',
        s015: 'Aktiveerimisoleku taastamiseks peate ühendama teleri internetiga',
        s016: 'Osa {0}',
        s017: 'Hooaeg {0}',
        s018: 'Vaatamata',
        s019: '{0} osa',
        s020: 'Lavastaja',
        s021: 'Käsikiri',
        s022: 'Näitlejad',
        s023: 'Video',
        s024: 'Audio',
        s025: 'Subtiitrid',
        s026: 'Puudub',

        // -- Library (section) --

        s027: 'filtreeritud',
        s028: ' - ',
        s029: 'Meediakogu on tühi',
        s030: 'Ühtegi vastet ei leitud',

        // -- Filters dialog --

        s031: 'Filtrid',
        s032: 'Kuva ainult Vaatamata',
        s033: 'Lähtesta',
        s034: 'Rakenda',

        // -- Settings dialog --

        s035: 'Üldine',
        s036: 'Videomängija',
        s037: 'Muuusikamängija',
        s038: 'Fotovaatur',
        s039: 'Juhtelemendid',
        s040: 'Kodukasutajad',
        s041: 'Konto',
        s042: 'Teave XPlay kohta',
        s043: 'Tavaseaded',
        s044: 'Liidese keel',
        s045: 'Tundmatu',
        s046: 'Kella vorming',
        s047: 'Jätka vaatamist',
        s048: 'Tunnusmuusika',
        s049: 'Ei',
        s050: 'Jah',
        s051: 'Kordus',
        s052: 'Ekraanisäästja',
        s053: 'Keelatud',
        s054: 'Meediahinnang',
        s055: 'Tärnid',
        s056: 'Number',
        s057: 'Meediapostrid',
        s058: 'Postrite kvaliteet',
        s059: 'Peamise meediapostri kvaliteet',
        s060: 'Meediapildid',
        s061: 'Näita',
        s062: 'Kuva meediapildid',
        s063: 'Kvaliteet',
        s064: 'Meediapiltide kvaliteet',
        s065: 'Läbipaistvus',
        s066: 'Meediapiltide läbipaistvus',
        s067: 'Häguefekt',
        s068: 'Meediapiltide häguefekt',
        s069: 'Taasesitus',
        s070: 'Taasesitusrežiim',
        s071: 'Järgmise osa automaatne esitamine',
        s072: 'Küsi',
        s073: 'Juhtelementide kuvamine',
        s074: 'Kursori liigutus',
        s075: 'Nupuvajutus',
        s076: 'Kursor või nupp',
        s077: 'Kino treilerid',
        s078: 'Kerimise samm',
        s079: 'Juhtelementide peitmine',
        s080: 'Transkodeerimine',
        s081: 'Kvaliteet',
        s082: 'Transkodeerimise kvaliteet',
        s083: 'Algne',
        s084: 'Helitugevus',
        s085: 'Transkodeerimise helitugevus',
        s086: 'Väike',
        s087: 'Suur',
        s088: 'Ülisuur',
        s089: 'Protokoll',
        s090: 'Transkodeerimise striimingu protokoll',
        s091: 'Otseesitus',
        s092: 'Väär',
        s093: 'Tõene',
        s094: 'Otsevoog',
        s095: 'Suurus',
        s096: 'Subtiitrite suurus',
        s097: 'Tilluke',
        s098: 'Väike',
        s099: 'Normaalne',
        s100: 'Suur',
        s101: 'Tohutu',
        s102: 'Koodileht (välised subtiitrid)',
        s103: 'Subtiitrite koodileht (välised subtiitrid)',
        s104: 'Asukoht (välised subtiitrid)',
        s105: 'Subtiitrite asukoht (välised subtiitrid)',
        s106: 'Värv (välised subtiitrid)',
        s107: 'Subtiitrite värv (välised subtiitrid)',
        s108: 'Valge',
        s109: 'Hõbedane',
        s110: 'Hall',
        s111: 'Must',
        s112: 'Lilla',
        s113: 'Punane',
        s114: 'Oranž',
        s115: 'Kollane',
        s116: 'Roheline',
        s117: 'Laimiroheline',
        s118: 'Sinine',
        s119: 'Helesinine',
        s120: 'Järjekord (kaustavaade)',
        s121: 'Järjekorra tüüp (kaustavaade)',
        s122: 'Algne',
        s123: 'Kohandatud',
        s124: 'Vorming',
        s125: 'Transkodeerimisvorming',
        s126: 'Bitikiirus',
        s127: 'Transkodeeimise bitikiirus',
        s128: 'Automaatne taasesitus',
        s129: 'Taasesituse aeg',
        s130: 'Korduv taasesitus',
        s131: 'Näita värvilist tausta',
        s132: 'Foto kuvakvaliteet',
        s133: 'Eelmine',
        s134: 'Järgmine',
        s135: 'Mängi/Paus',
        s136: 'Lõpeta',
        s137: 'Tagasi',
        s138: 'Edasi',
        s139: 'Kiire tagasikerimine',
        s140: 'Kiire edasikerimine',
        s141: 'Punane nupp',
        s142: 'Roheline nupp',
        s143: 'Sinine nupp',
        s144: 'Kollane nupp',
        s145: 'Kodukasutajad',
        s146: 'Eemalda',
        s147: 'Ainult kaks kasutajat saavad olla kohalikud kodukasutajad.<br>Kui soovite rohkem kodukasutajaid, kasutage Plexi kodukasutajate funktsiooni.',
        s148: 'Siin saate luua rühma kasutajatest, kes kõik koos kasutavad Plexi.<br/>Näiteks võivad olla kasutajateks perekond (vanemad ja lapsed), <br/>kes kasutavad Plexi teleris, mis on ühendatud sama Plex Media Serveriga.',
        s149: 'Plex teenustega ühendamine ...',
        s150: 'Plexi konto sidumiseks kohaliku kodukasutajana<br/>minge <span style="color:#FFA500">https://plex.tv/link</span> ja sisestage eeltoodud kood.',
        s151: 'Lisage kohalik kodukasutaja',
        s152: 'Sisselogitud nimega',
        s153: 'Kasutaja ID',
        s154: 'Aktiveerimise olek',
        s155: 'TUNDMATU',
        s156: 'Plexi konto eemaldamine',
        s157: 'See programmi versioon on piiratud kasutusajaga.<br/>Piirangu eemaldamiseks palun külastage meie veebi <span style="color:#FFA500">https://xplay.itkey.ru</span><br>ja ärge unustage oma kasutaja ID-d.',
        s158: 'Plex Media Serveri mitteametlik klient.',
        s159: 'Logod, firmamärgid ja muud registreeritud kaubamärgid kuuluvad<br>nende omanikele. Kõik õigused on kaitstud.',
        s160: 'Vaikesätete taastamine',

        // -- ... --

        s161: 'Meedia vaadatud/vaatamata oleku ümberlülitamine ...',
        s162: 'Aktiveerimisoleku taastamiseks ja taasesituse piirangu eemaldamiseks <br/> peate ühendama teleri internetiga',
        s163: 'Taasesituspiirangu eemaldamiseks peate ühendama teleri internetiga',
        s164: 'See programmi versioon on piiratud kasutusajaga.<br/>Sa ei saa enam meediafaile mängida.',
        s165: 'Taasesitusjärjekorra moodustamine ...',
        s166: 'Tundmatu žanr',
        s167: 'Oops! Midagi läks valesti',
        s168: 'Valitud kasutaja kasutamine pole võimalik. <br/> Suhtlemine Plex API-ga ebaõnnestus.',
        s169: 'Vale PIN-kood',
        s170: 'Kasutajateabe küsimine ...',
        s171: 'Vale PIN-kood. <br/> Korduvad katsed võivad sisselogimise ajutiselt keelata',
        s172: 'Ei saa töödelda kasutajateavet. <br/> Suhtlemine Plex API-ga ebaõnnestus',
        s173: 'Proovime ühendada {0} ...',
        s174: 'Oops! Midagi läks valesti ja ei saanud ühendada {0}',
        s175: 'Edukalt ühendatud {0}',
        s176: 'Ühendamine {0} ...',
        s177: 'Oops! Midagi läks valesti ja autentimine {0} ebaõnnestus',
        s178: 'Oops! Midagi läks valesti ja suhtlemine {0} ebaõnnestus',
        s179: 'Ei saa laadida serverite nimekirja Plex API-st',
        s180: 'Suhtlemine Plex API-ga ebaõnnestus',
        s181: 'Konto andmete päring ...',
        s182: 'Ühendamine plex.tv ...',
        s183: 'Avalehe teabe taotlemine ...',
        s184: 'Oops! Midagi läks valesti ja serveri vastuse töötlemine ebaõnnestus',
        s185: 'Avaleht',
        s186: 'Pooleli',
        s187: 'Viimati lisatud',
        s188: 'Jätka kohast {0}',
        s189: 'Alusta algusest',
        s190: 'Jätka mängimist',
        s191: 'Treilerid',
        s192: 'Helirajad',
        s193: 'Subtiitrid',
        s194: 'Veel tegevusi',
        s195: 'Kas soovite kindlasti selle üksuse failisüsteemist kustutada?',
        s196: 'Kustuta',
        s197: 'Meedia kustutamine failisüsteemist ...',
        s198: 'Meediateabe päring ...',
        s199: 'Treiler',
        s200: 'Meedia',
        s201: 'Transkodeeri',
        s202: 'Meediapostri laadimine ...',
        s203: 'Meediapiltide laadimine ...',
        s204: 'Oops! Midagi läks valesti ja meediateabe allalaadimine ebaõnnestus',
        s205: 'Sorteerimine',
        s206: '14 postrit',
        s207: '33 postrit',
        s208: '27 postrit (pealkirjadeta)',
        s209: '48 postrit (pealkirjadeta)',
        s210: 'Ruudustiku suurus',
        s211: 'Tüübi järgi',
        s212: 'Esitajate järgi',
        s213: 'Filmide järgi',
        s214: 'Seriaalide järgi',
        s215: 'Kuvarežiim',
        s216: 'Kataloogide järgi',
        s217: 'Taasesitusjärjekorra loomine ...',
        s218: 'Meediakogu üksuste taotlemine ...',
        s219: 'Oops! Midagi läks valesti suhtlemisel {0}',
        s220: 'Meediakogu üksuste taotlemine ...',
        s221: 'Värskenda',
        s222: 'Vaata ruudustiku suurust',
        s223: 'Taaskäivita esitusjärjekord ...',
        s224: 'Kas mängida järgmine osa?',
        s225: 'Mängi',
        s226: 'Oops! Midagi läks valesti ja meedia vaadatud/vaatamata oleku ümberlülitamine ebaõnnestus',
        s227: 'Katkestasite video taasesituse',
        s228: 'Võrgu viga põhjustas video allalaadimise poolelijätmise',
        s229: 'Video taasesitus katkestati rikutud video tõttu või teie brauser ei toeta vastavat videovormingut',
        s230: 'Videot ei õnnestunud laadida serveri või võrgu vea tõttu või vastavat videovormingut ei toetata',
        s231: 'Ilmnes tundmatu viga (määratlemata kood)',
        s232: 'Ilmnes tundmatu viga',
        s233: 'Demoperiood lõppeb {0} päeva pärast',
        s234: 'Demoperiood lõppeb {0}',
    });
