var i18n = (
    {
        s000: 'Traduction française par Fred HALFON <span style="color:#FFA500">frederic.halfon@laposte.net</span>',
        s001: 'Redémarrer',
        s002: 'Email pour le support et les avis <span style="color:#FFA500">xplay@itkey.ru</span> ou visiter le forum <span style="color:#FFA500">http://xplay.itkey.ru/forum/</span>',
        s003: 'Pour vous connecter, allez sur <span style="color:#FFA500">https://plex.tv/link</span> et saisissez le code ci-dessus.',
        s004: 'Réessayer de lier le compte',
        s005: 'Liste des serveurs disponibles pour {0}',
        s006: 'Aucun Plex Media Server disponible',
        s007: 'Annuler',
        s008: 'Dé-lier {0}',
        s009: 'Saisisez le code PIN de votre compte Plex',
        s010: 'Continuer à regarder',
        s011: 'Ajout récents',
        s012: 'Rien à afficher sur le dashboard',
        s013: 'Période de test expirée',
        s014: 'Vous pouvez encore démarrer {0} fois en mode déconnecté. Merci de connecter votre TV à Internet.',
        s015: 'Vous devez connecter votre TV à Internet pour restaurer le statut d\'activation',
        s016: 'Episode {0}',
        s017: 'Saison {0}',
        s018: 'Non vu',
        s019: '{0} Parties',
        s020: 'Directeur',
        s021: 'Auteur',
        s022: 'Casting',
        s023: 'Vidéo',
        s024: 'Audio',
        s025: 'Sous-titres',
        s026: 'Aucun',

        // -- Library (section) --

        s027: 'filtré',
        s028: ' de ',
        s029: 'Bibliothèque vide',
        s030: 'Aucune correspondance trouvée',

        // -- Filters dialog --

        s031: 'Filtrer',
        s032: 'N\'afficher que les éléments non vus',
        s033: 'Réinitialiser',
        s034: 'Appliquer',

        // -- Settings dialog --

        s035: 'Général',
        s036: 'Lecteur Vidéo',
        s037: 'Lecteur Audio',
        s038: 'Visionneuse Photo',
        s039: 'Contrôles',
        s040: 'Utilisateurs locaux',
        s041: 'Compte',
        s042: 'A propos',
        s043: 'Commun',
        s044: 'Langue de l\'interface',
        s045: 'Inconnu',
        s046: 'Format de l\'heure',
        s047: 'Continuer à regarder',
        s048: 'Thèmes Audio',
        s049: 'Non',
        s050: 'Oui',
        s051: 'Boucle',
        s052: 'Economiseur d\'écran',
        s053: 'Désactivé',
        s054: 'Note',
        s055: 'Etoiles',
        s056: 'Nombres',
        s057: 'Affiches',
        s058: 'Qualité des affiches',
        s059: 'Qualité de l\'affiche principale',
        s060: 'Média arts',
        s061: 'Afficher',
        s062: 'Afficher les Media arts',
        s063: 'Qualité',
        s064: 'Qualité des Media arts',
        s065: 'Opacité',
        s066: 'Opacité des Media arts',
        s067: 'Effet de flou',
        s068: 'Effet de flou des Media arts',
        s069: 'Lecture',
        s070: 'Mode de lecture',
        s071: 'Episode suivant automatique',

        // Auto play next episode
        s072: 'Demander',

        s073: 'Pour afficher les contrôles',
        s074: 'Déplacement du curseur',
        s075: 'Clic sur un bouton',
        s076: 'Curseur ou bouton',
        s077: 'Bandes annonces',
        s078: 'Intervalle de recherche',
        s079: 'Disparition des contrôles en',
        s080: 'Transcodage',
        s081: 'Qualité',
        s082: 'Qualité du transcodage',
        s083: 'Originale',
        s084: 'Boost Audio',
        s085: 'Transcodage du boost audio',
        s086: 'Petit',
        s087: 'Grand',
        s088: 'Enorme',
        s089: 'Protocole',
        s090: 'Protocole de transcodage du streaming',
        s091: 'Lecture directe',
        s092: 'Non',
        s093: 'Oui',
        s094: 'Streamer directement',
        s095: 'Taille',
        s096: 'Taille des sous-titres',
        s097: 'Très petite',
        s098: 'Petite',
        s099: 'Normale',
        s100: 'Grande',
        s101: 'Enormes',
        s102: 'Codepage (externe)',
        s103: 'Codepage des sous titres (externes seulement)',
        s104: 'Position (externe)',
        s105: 'Position des sous-titres (externes seulement)',
        s106: 'Couleur (externe)',
        s107: 'Couleur des sous-titres (externes seulement)',
        s108: 'Blanc',
        s109: 'Argent',
        s110: 'Gris',
        s111: 'Noir',
        s112: 'Violet',
        s113: 'Rouge',
        s114: 'Orange',
        s115: 'Jaune',
        s116: 'Vert',
        s117: 'Citron Vert',
        s118: 'Bleu',
        s119: 'Bleu clair',
        s120: 'Liste (vue répertoire)',
        s121: 'Type de liste (vue répertoire)',
        s122: 'Natif',
        s123: 'Local',
        s124: 'Format',
        s125: 'Format de transcodage',
        s126: 'Bitrate',
        s127: 'Bitrate de transcodage',
        s128: 'Démarrer automatiquement',
        s129: 'Timeout de lecture',
        s130: 'Lecture en boucle',
        s131: 'Afficher la couleur de fond',
        s132: 'Qualité d\'affichage des photos',
        s133: 'Précedent',
        s134: 'Suivant',
        s135: 'Démarrer/Pause',
        s136: 'Stop',
        s137: 'Retour',
        s138: 'Avance',
        s139: 'Retour rapide',
        s140: 'Avance rapide',
        s141: 'Bouton rouge',
        s142: 'Bouton vert',
        s143: 'Bouton bleu',
        s144: 'Bouton jaune',
        s145: 'Utilisateurs locaux',
        s146: 'Supprimer',
        s147: 'Un maximum de deux utilisateurs est autorisé en mode utilisateur local.<br>Si vous souhaitez d\'avantage d\'utilisateurs mer d\'utilisateur la gestion native de Plex.',
        s148: 'Vous pouvez définir ici, un groupe d\'utilisateurs qui utilisent Plex ensemble.<br/>Ce peut être par exemple une famille (parents et enfants) qui utilisent tous <br/> Plex sur un téléviseur connecté au même serveur Plex Media dans leur maison.',
        s149: 'Connexion aux services Plex ...',
        s150: 'Pour lier un compte Plex en tant qu\'utilisateur local <br/>visiter <span style="color:#FFA500">https://plex.tv/link</span> et saisissez le code ci-dessus.',
        s151: 'Ajouter un utilisateur local',
        s152: 'Connecté en tant que',
        s153: 'Identifiant utilisateur',
        s154: 'Statut d\'activation',
        s155: 'INCONNU',
        s156: 'Désaffecter le compte Plex',
        s157: 'Cette version de l\'application peut être utilisée pour une période de temps limitée.<br/>Pour retirer cette limitation, merci de visiter notre site <span style="color:#FFA500">https://xplay.itkey.ru</span><br> et n\'oubliez pas votre identifiant utilisateur.',
        s158: 'Un client non officiell pour Plex Media Server.',
        s159: 'Logos, les marques déposées appartiennent à leurs propriétaires respectifs.<br>Tous droits réservés.',
        s160: 'Réinitialiser',

        // -- ... --

        s161: 'Inversion du statut de lecture du média ...',
        s162: 'Vous devez connecter votre TV à Internet pour restaurer le statut d\'activation <br/> et supprimer les restrictions de lecture',
        s163: 'Vous devez connecter votre TV à Internet pour supprimer les restrictions de lecture',
        s164: 'Cette version de l\'application peut etre utilisée pour un temps limité. <br/> Vous ne pouvez désormais plus lire de fichiers.',
        s165: 'Creation de la liste de lecture ...',
        s166: 'Genre inconnu',
        s167: 'Quelque chose s\'est mal passé',
        s168: 'Impossible d\'utiliser l\'utilisateur sélectionné. <br/> Impossible de communiquer avec l\'API de Plex.',
        s169: 'Code PIN incorrect',
        s170: 'Récupération des informations de l\'utilisateur ...',
        s171: 'Code PIN incorrect. <br/> Des tentatives répétées peuvent désactiver temporairement la connection',
        s172: 'Impossible de traiter les informations utilisateur <br/>La communication avec l\'API Plex a échouée',
        s173: 'Connection à {0} ...',
        s174: 'Un problème est survenu impossible de se connecter à {0}',
        s175: 'Connecté avec succès à {0}',
        s176: 'Connection à {0} ...',
        s177: 'Un problème est survenu et l\'authentification à {0} a échoué',
        s178: 'Un problème est survenu et la communication avec {0} a échoué',
        s179: 'Impossible de charger la liste des serveurs Plex via l\'API Plex',
        s180: 'Impossible de contacter l\'API Plex',
        s181: 'Récupération des informations du compte ...',
        s182: 'Connection à plex.tv ...',
        s183: 'Récupération du tableau de bord ...',
        s184: 'Un problème est survenu impossible de traiter la réponse du serveur',
        s185: 'Accueil',
        s186: 'Continuer à regarder',
        s187: 'Ajouté récemment',
        s188: 'Reprendre depuis {0}',
        s189: 'Lire depuis le début',
        s190: 'Reprendre la lecture',
        s191: 'Trailers',
        s192: 'Pistes audios',
        s193: 'Sous-titres',
        s194: 'Autres actions',
        s195: 'Etes-vous de vouloir supprimer ce fichier ?',
        s196: 'Supprimer',
        s197: 'Suprression du fichier ...',
        s198: 'Récupération des informations du média ...',
        s199: 'Trailer',
        s200: 'Média',
        s201: 'Transcoder',
        s202: 'Chargement de l\'affiche ...',
        s203: 'Chargement du média art ...',
        s204: 'Un problème est survenu impossible de récuperer les informations du média',
        s205: 'Trier',
        s206: '14 affiches',
        s207: '33 affiches',
        s208: '27 affiches (sans les titres)',
        s209: '48 affiches (sans les titres)',
        s210: 'Affichage de la grille',
        s211: 'Par Type',
        s212: 'Par Artistes',
        s213: 'Par Films',
        s214: 'Par Séries TV',
        s215: 'Mode d\'affichage',
        s216: 'Par répertoire',
        s217: 'Création de la liste de lecture ...',
        s218: 'Récupération des élements de la bibliothèque ...',
        s219: 'Un problème est survenu lors de la communiqaction avec {0}',
        s220: 'Récupération des élements de la bibliothèque ...',
        s221: 'Rafraîchir',
        s222: 'Taille de grille',
        s223: 'Reprise de la liste de lecture ...',
        s224: 'Jouer l\'épisode suivant ?',
        s225: 'Jouer',
        s226: 'Un problème est survenu, impossible de changer le statut de visualisation du média',
        s227: 'Vous avez annulé la lecture du média',
        s228: 'Un erreur réseau a empeché le téléchargemnt de la vidéo',
        s229: 'La lecteur de la vidéo a été interrompue suite à un problème de corruption ou parce que la vidéo utilise des fonctionnalités que votre navigateur ne supporte pas',
        s230: 'La vidéo ne peut pas être lue, soit à cause du serveur soit à cause du réseau soit parce que son format n\'est pas supporté',
        s231: 'Une erreur inconnue est survenue (code indéfini)',
        s232: 'Une erreur inconnue est survenue',
        s233: 'La période de démo expire dans {0} jour(s)',
        s234: 'La période de démo expire en {0}',
        s235: 'S{0}',
        s236: 'E{0}',
        s237: 'Paramètres',

        // Auto play next episode
        s238: 'Oui',

        //
        s239: 'Rechercher dans {0}',
        s240: 'h [h] mm [min]',
        s241: 'mm [min] ss [sec]',
        s242: 'mm [min]',
        s243: 'ss [sec]'
    });