var i18n = (
    {
        s000: 'Traduction française par Fred HALFON <span style="color:#FFA500">xplay@itkey.ru</span>',
        s001: 'Redémarrer',
        s002: 'Email pour le support et les avis <span style="color:#FFA500">xplay@itkey.ru</span> ou visiter le forum <span style="color:#FFA500">http://xplay.itkey.ru/forum/</span>',
        s003: 'Pour vous connecter, allez sur <span style="color:#FFA500">https://plex.tv/link</span> et saisissez le code ci-dessus.',
        s004: 'Réessayer l\'association du compte',
        s005: 'Liste des serveurs disponibles pour {0}',
        s006: 'Auncun serveur Plex disponible',
        s007: 'Annuler',
        s008: 'Dissocier {0}',
        s009: 'Saissisez le code PIN de votre compte Plex',
        s010: 'Continuer à regarder',
        s011: 'Ajouté recemment',
        s012: 'Rien à afficher sur le tableau de bord',
        s013: 'Période d\'essai expirée',
        s014: 'Il vous reste {0} démarrage en mode hors ligne. Merci de connecter votre TV à Internet.',
        s015: 'Vous devez connecter votre TV à Internet pour restaurer le statut d\'activation',
        s016: 'Épisode {0}',
        s017: 'Saison {0}',
        s018: 'Non vu',
        s019: '{0} Parties',
        s020: 'Réalisateur',
        s021: 'Scénariste',
        s022: 'Casting',
        s023: 'Vidéo',
        s024: 'Audio',
        s025: 'Sous-titres',
        s026: 'Aucun',

        // -- Library (section) --

        s027: 'filtré',
        s028: ' de ',
        s029: 'Bibliothèque vide',
        s030: 'Aucune correspondance trouvée',

        // -- Filters dialog --

        s031: 'Filtres',
        s032: 'Ne montrer que les éléments non vus',
        s033: 'Réinitialiser',
        s034: 'Appliquer',

        // -- Settings dialog --

        s035: 'Général',
        s036: 'Lecteur Vidéo',
        s037: 'Audio player',
        s038: 'Gallerie photos',
        s039: 'Contrôles',
        s040: 'Utilisateurs locaux',
        s041: 'Compte',
        s042: 'À propos',
        s043: 'Commun ???',
        s044: 'Langue de l\'interface',
        s045: 'Inconnu',
        s046: 'Format de l\'heure',
        s047: 'Continuer à regarder',
        s048: 'Thême Audio',
        s049: 'Non',
        s050: 'Oui',
        s051: 'Boucler',
        s052: 'Écran de veille',
        s053: 'Désactivé',
        s054: 'Note',
        s055: 'Étoiles',
        s056: 'Nombre',
        s057: 'Affiches',
        s058: 'Qualité des affiches',
        s059: 'Qualité des affiches media principal',
        s060: 'Media arts',
        s061: 'Afficher',
        s062: 'Afficher les Media arts',
        s063: 'Qualité',
        s064: 'Qualité des Media arts',
        s065: 'Opacité',
        s066: 'Opacité des Media art',
        s067: 'Effet de flou',
        s068: 'Effet de flou des Media arts',
        s069: 'Lecture',
        s070: 'Mode de lecture',
        s071: 'Jouer l\'épisode suivant automatiquement',

        // Auto play next episode
        s072: 'Demander',

        s073: 'Déclencheur d\'affichage des contrôles',
        s074: 'Déplacement du curseur',
        s075: 'Appui sur un bouton',
        s076: 'Curseur ou bouton',
        s077: 'Bandes annonce',
        s078: 'Intervalle de recherche',
        s079: 'Temps avant disparition des contrôles',
        s080: 'Transcodage',
        s081: 'Qualité',
        s082: 'Qualité du transcodage',
        s083: 'Original',
        s084: 'Booster l\'audio',
        s085: 'Transcodage du boost audio',
        s086: 'Petit',
        s087: 'Grand',
        s088: 'Énorme',
        s089: 'Protocole',
        s090: 'Protocole de transcodage du streaming',
        s091: 'Lecture sans transcodage',
        s092: 'Faux',
        s093: 'Vrai',
        s094: 'Streamer directement',
        s095: 'Taille',
        s096: 'Taille des sous-titres',
        s097: 'Très petit',
        s098: 'Petit',
        s099: 'Normal',
        s100: 'Grand',
        s101: 'Énorme',
        s102: 'Codepage (externe)',
        s103: 'Codepage des sous titres (externes seulement)',
        s104: 'Position (externe)',
        s105: 'Position des sous-titres (externes seulement)',
        s106: 'Couleur (externe)',
        s107: 'Couleur des sous-titres (externes seulement)',
        s108: 'Blanc',
        s109: 'Argent',
        s110: 'Gris',
        s111: 'Noir',
        s112: 'Violet',
        s113: 'Rouge',
        s114: 'Orange',
        s115: 'Jaune',
        s116: 'Vert',
        s117: 'Vert Citron',
        s118: 'Bleu',
        s119: 'Bleu clair',
        s120: 'Liste (vue répertoire)',
        s121: 'Type de liste (vue répertoire)',
        s122: 'Natif',
        s123: 'Local',
        s124: 'Format',
        s125: 'Format de transcodage',
        s126: 'Bitrate',
        s127: 'Bitrate de transcodage',
        s128: 'Démarrer automtiquement',
        s129: 'Timeout de lecture',
        s130: 'Lecture en boucle',
        s131: 'Afficher la couleur de fond',
        s132: 'Qualité d\'affichage des photos',
        s133: 'Précedent',
        s134: 'Suivant',
        s135: 'Lecture/Pause',
        s136: 'Stop',
        s137: 'Reculer',
        s138: 'Avancer',
        s139: 'Retour rapide',
        s140: 'Avance rapide',
        s141: 'Bouton rouge',
        s142: 'Bouton vert',
        s143: 'Bouton bleu',
        s144: 'Bouton jaune',
        s145: 'Home users',
        s146: 'Supprimer',
        s147: 'Seul deux utilisateurs peuvent être utilisés comme utilisateur local.<br>Si vous souhaitez d\'avantage d\'utilisateurs merci d\'utilisateur l\'application Plex native.',
        s148: 'Vous pouvez définir ici un groupe d\'utilisateurs qui utilisent Plex ensemble.<br/>Ce peut être par exemple une famille (parents et enfants) qui utilisent tous <br/> Plex sur un téléviseur connecté au même serveur Plex Media dans leur maison.',
        s149: 'Connexion aux services Plex ...',
        s150: 'Pour lier un compte Plex en tant qu\'utilisateur local <br/>visiter <span style="color:#FFA500">https://plex.tv/link</span> et saisissez le code ci-dessus.',
        s151: 'Ajouter un utilisateur local',
        s152: 'Connecté en tant que',
        s153: 'Identifiant utilisateur',
        s154: 'Statut d \'activation',
        s155: 'INCONNU',
        s156: 'Déassoier le compte Plex',
        s157: 'Cette version de l\'application peut être utilisée pour une période de temps limitée.<br/>Pour retirer cette limitation, merci de visiter notre site <span style="color:#FFA500">https://xplay.itkey.ru</span><br> et n\'oubliez pas votre identifiant utilisateur.',
        s158: 'Un client non officiell pour Plex Media Server.',
        s159: 'Logos et marques déposées appartiennent à leurs propriétaires respectifs.<br>Tous droits réservés.',
        s160: 'Réinitialiser aux vqleurs pqr défaut',

        // -- ... --

        s161: 'Changement du status de visualisation ...',
        s162: 'Vous devez connecter votre TV à Internet pour restaurer le statut d\'activation <br/> et supprimer les restrictions de lecture',
        s163: 'Vous devez connecter votre TV à Internet pour supprimer les restrictions de lecture',
        s164: 'Cette version de l\'application peut etre utilisée pour un temps limité. <br/> Vous ne pouvez désormais plus lire de fichiers.',
        s165: 'Création de la liste de lecture ...',
        s166: 'Genre inconnu',
        s167: 'Ohh mince, quelque chose a mal tourné',
        s168: 'Impossible d\'utiliser l\'utilisateur sélectionné. <br/> Impossible de communiquer avec l\'API de Plex.',
        s169: 'Code PIN incorrect',
        s170: 'Récupération des informations utilisateur ...',
        s171: 'Code PIN incorrect. <br/> Des tentatives répétées peuvent désactiver temporairement la connection',
        s172: 'Impossible de traiter les informations utilisateur <br/>La communication avec l\'API Plex à échouée',
        s173: 'Connection à {0} ...',
        s174: 'Ohh mince, un problème est survenu impossible de se connecter à {0}',
        s175: 'Connecté avec succès à {0}',
        s176: 'Connexion à {0} ...',
        s177: 'Ohh mince, un problème est survenu et l\'authentification à {0} a échoué',
        s178: 'Ohh mince, un problème est survenu et la communication avec {0} a échoué',
        s179: 'Impossible de charger la liste des serveurs Plex via l''API Plex',
        s180: 'Impossible de contacter l\'API Plex',
        s181: 'Récupération des informations du compte ...',
        s182: 'Connection à plex.tv ...',
        s183: 'Récupération du tableau de bord ...',
        s184: 'Ohh mince, un problème est survenu impossible de traiter la réponse du serveur',
        s185: 'Accueil',
        s186: 'Poursuivre la lecture',
        s187: 'Ajouté récemment',
        s188: 'Reprendre depuis {0}',
        s189: 'Lire depuis le début',
        s190: 'Reprendre la lecture',
        s191: 'Bandes annonces',
        s192: 'Pistes audios',
        s193: 'Sous-titres',
        s194: 'Plus d\'actions',
        s195: 'Etes-vous de vouloir supprimer ce fichier du disque?',
        s196: 'Supprimer',
        s197: 'Suprression du fichier sur le disque...',
        s198: 'Récupération des information du média ...',
        s199: 'Bande annonce',
        s200: 'Média',
        s201: 'Transcoder',
        s202: 'Chargement de l\'affiche ...',
        s203: 'Chargement du media art ...',
        s204: 'Ohh mince, un problème est survenu impossible de récuperer les informations du média',
        s205: 'Tri en cours',
        s206: '14 affiches',
        s207: '33 affiches',
        s208: '27 affiches (sans titres)',
        s209: '48 affiches (sans titres)',
        s210: 'Taille de la grille',
        s211: 'Par Type',
        s212: 'Par Artistes',
        s213: 'Par Films',
        s214: 'Par séries TV',
        s215: 'Mode d\'affichage',
        s216: 'Par répertoire',
        s217: 'Création de la liste de lecture ...',
        s218: 'Récupération des élements de la bibliothèque ...',
        s219: 'Un problème est survenu lors de la communicaction avec {0}',
        s220: 'Récupération des élements de la bibliothèque ...',
        s221: 'Rafraîchir',
        s222: 'Taille de grille',
        s223: 'Reprise de la liste de lecture ...',
        s224: 'Jouer l\'épisode suivant ?',
        s225: 'Jouer',
        s226: 'Ohh mince, un problème est survenu, impossible de changer le statut de visualisation du média',
        s227: 'Vous avez annulé la lecture du média',
        s228: 'Un erreur réseau a empeché le téléchargemnt de la vidéo',
        s229: 'La lecteur de la vidéo a été interrompue suite à un problème de corruption ou parce que la vidéo utilise des fonctionnalités que votre navigateur ne supporte pas',
        s230: 'La vidéo ne peut pas être lue, soit à cause du serveur soit à cause du réseau soit parce que son format n''est pas supporté',
        s231: 'Une erreur inconnue est survenue (code indéfini)',
        s232: 'Une erreur inconnue est survenue',
        s233: 'La période de démo expire dans {0} jour(s)',
        s234: 'La période de démo expire en {0}',
        s235: 'S{0}',
        s236: 'E{0}',
        s237: 'Paramètres',

        // Auto play next episode
        s238: 'Oui',

        //
        s239: 'Rechercher dans {0}',
        s240: 'h [h] mm [min]',
        s241: 'mm [min] ss [sec]',
        s242: 'mm [min]',
        s243: 'ss [sec]'
    });
