var i18n = (
    {
        s000: 'Béarla ag by Darren McEntee <span style="color:#FFA500">darren.mcentee@gmail.com</span>',
        s001: 'Athshlánú',
        s002: 'Ríomhphost le haghaidh tacaíochta agus aiseolas <span style="color:#FFA500">xplay@itkey.ru</span> nó tabhair cuairt ar fhóram <span style="color:#FFA500">http://xplay.itkey.ru/forum/</span>',
        s003: 'Chun comhartha isteach, tabhair cuairt ar <span style="color:#FFA500">https://plex.tv/link</span> agus cuir isteach an cód thuas.',
        s004: 'Athraigh cuntas a nascadh',
        s005: 'Tá liosta na freastalaithe atá ar fáil le haghaidh {0}',
        s006: 'Níl aon Freastalaithe Meáin Plex ar fáil',
        s007: 'Cealaigh',
        s008: 'Díghlasáil {0}',
        s009: 'Cuir isteach do chód PIN cuntais Plex',
        //s010: 'Leanúint ar aghaidh ag breathnú',
        s010: 'Lean ar aghaidh',
        s011: 'Le déanaí curtha leis',
        s012: 'Ní dhéanfaidh aon ní a thaispeánfar ar an mbord',
        s013: 'Tréimhse na tréimhse tástála in éag',
        s014: 'Tá tú ag tosú as líne {0} ar chlé. Ceangail do theilifís ar an Idirlíon le do thoil. ',
        s015: 'Ní mór duit do theilifís a nascadh ar an Idirlíon chun stádas gníomhachtaithe a athbhunú',
        s016: 'Eipeasóid {0}',
        s017: 'Séasúr {0}',
        s018: 'Unwatched',
        s019: '{0} Páirteanna',
        s020: 'Stiúrthóir',
        s021: 'Scríbhneoir',
        s022: 'Cast',
        s023: 'Fís',
        s024: 'Fuaime',
        s025: 'Fotheidil',
        s026: 'Níl aon cheann',


        // -- Library (section) --

        s027: 'Scagtha',
        s028: 'de',
        s029: 'Leabharlann Folamh',
        s030: 'Ní bhfuarthas aon matches',

        // -- Filters dialog --

        s031: 'Scagairí',
        s032: 'Taispeáin unwatched amháin',
        s033: 'Athshocraigh',
        s034: 'Iarratas',

        // -- Settings dialog --

        s035: 'Ginearálta',
        s036: 'Imreoir físeáin',
        s037: 'Seinnteoir ceoil',
        s038: 'Breathnóir grianghraf',
        s039: 'Rialuithe',
        s040: 'Úsáideoirí baile',
        s041: 'Cuntais',
        s042: 'Maidir',
        s043: 'Coitianta',
        s044: 'Teanga Chomhéadain',
        s045: 'Anaithnid',
        s046: 'Formáid clog',
        //s047: 'Leanúint ar aghaidh ag breathnú',
        s047: 'Lean ar aghaidh',
        s048: 'Téama fuaime',
        s049: 'Níl',
        s050: 'Tá',
        s051: 'Lúb',
        s052: 'Spárálaíscáileáin',
        s053: 'Míchumas',
        s054: 'Meáin rátála',
        s055: 'Réaltaí',
        s056: 'Uimhir',
        s057: 'Póstaeir Meáin',
        s058: 'Caighdeán póstaeir',
        s059: 'Caighdeán póstaer príomhmheáin',
        s060: 'Na healaíona meán',
        s061: 'Taispeáin',
        s062: 'Taispeáin ealaín na meáin',
        s063: 'Caighdeán',
        s064: 'Caighdeán ealaíne na meáin',
        s065: 'Opacity',
        s066: 'Mionchaighdeán ealaíne',
        s067: 'Éifeacht blúrach',
        s068: 'Éifeacht meabhrach ealaíon na meáin',
        s069: 'Athsheinm',
        s070: 'Modh athsheinm',
        s071: 'Auto imirt an chéad eachtra eile',

        // Auto play next episode
        s072: 'Iarr',

        s073: 'Rialuithe múscail',
        s074: 'Bogadh cúrsóra',
        s075: 'Brúigh cnaipe',
        s076: 'Cúrsóir nó cnaipe',
        s077: 'Leantóirí Cinema',
        s078: 'Idirghabháil lorg',
        s079: 'Rialú am am ar fad',
        s080: 'Aistriú',
        s081: 'Caighdeán',
        s082: 'Caighdeán trascodála',
        s083: 'Bunaidh',
        s084: 'Fuaim fuaime',
        s085: 'Aistriú fuaime trascodála',
        s086: 'Beaga',
        s087: 'Móra',
        s088: 'Ollmhór',
        s089: 'Prótacal',
        s090: 'Aistriú prótacal sruthúcháin',
        s091: 'Súgradh díreach',
        s092: 'Bréagach',
        s093: 'Fíor',
        s094: 'Sreang díreach',
        s095: 'Méid',
        s096: 'Méid na bhfotheidealáin',
        s097: 'Tiny',
        s098: 'Beaga',
        s099: 'Gnáth',
        s100: 'Big',
        s101: 'Ollmhór',
        s102: 'Cód leathanach (seachtrach)',
        s103: 'Leathanach cód na bhfotheidealáin (seachtrach amháin)',
        s104: 'Seasamh (seachtrach)',
        s105: 'Seasamh na bhfotheidealáin (seachtrach amháin)',
        s106: 'Dath (seachtrach)',
        s107: 'Dath na bhfotheidealáin (seachtrach amháin)',
        s108: 'Bán',
        s109: 'Silver',
        s110: 'Liath',
        s111: 'Dubh',
        s112: 'Corcra',
        s113: 'Dearg',
        s114: 'Orange',
        s115: 'Buí',
        s116: 'Glas',
        s117: 'Aoil',
        s118: 'Gorm',
        s119: 'Solas gorm',
        s120: 'Cuail (amharc fillteán)',
        s121: 'Cineál na cuaise (amharc fillteán)',
        s122: 'Dúchasach',
        s123: 'Áitiúil',
        s124: 'Formáid',
        s125: 'Formáid transcoding',
        s126: 'Giotán',
        s127: 'Transcoding bitrate',
        s128: 'Athsheinm Autostart',
        s129: 'Amchlár athsheinm',
        s130: 'Athsheinm Loopback',
        s131: 'Taispeáin cúlra dath',
        s132: 'Caighdeán taispeáint grianghraf',
        s133: 'Roimhe Seo',
        s134: 'Ar Aghaidh',
        s135: 'Seinn / Sos',
        s136: 'Stop',
        s137: 'Athdhéanamh',
        s138: 'Ar aghaidh',
        s139: 'Athdhíol Go Tapa',
        s140: 'Aghaidh Go Tapa',
        s141: 'Cnaipe Dearg',
        s142: 'Cnaipe Glas',
        s143: 'Cnaipe Gorm',
        s144: 'Button Buí',
        s145: 'Úsáideoirí baile',
        s146: 'Bain',
        s147: 'Ní féidir ach dhá úsáideoir a úsáid mar úsáideoirí baile áitiúla.<br>Más mian leat níos mó úsáideoirí baile, bain úsáid as an ghné Úsáideoirí Baile Plex dúchais.',
        s148: 'Anseo is féidir leat grúpa úsáideoirí a bhunú go n-úsáideann Plex go léir le chéile.<br/>Mar shampla, d\'fhéadfadh go mbeadh teaghlaigh úsáideoirí (tuismitheoirí agus leanaí) go<br/>n-úsáideann an  go léir Plex ar an teilifís a bhaineann leis an Freastalaí<br/> Meáin Plex céanna ina dteach. ',
        s149: 'Ag nascadh le seirbhísí Plex ...',
        s150: 'Chun nasc Plex a nascadh mar <br/> úsáideoir baile áitiúil <span style="color:#FFA500">https://plex.tv/link</span> agus cuir isteach an cód thuas.',
        s151: 'Cuir úsáideoir baile áitiúil isteach',
        s152: 'Sínithe isteach mar',
        s153: 'ID Úsáideora',
        s154: 'Stádas gníomhachtaithe',
        s155: 'NEACHTAÍ',
        s156: 'Unlink Plex account',
        s157: 'Tá tréimhse teoranta úsáide ag an leagan seo.<br/>Chun teorainn a bhaint, tabhair cuairt ar ár suíomh gréasáin <span style="color:#FFA500">https://xplay.itkey.ru</span><br>agus ná déan dearmad d\'ID úsáideora. ',
        s158: 'Cliant neamhoifigiúil do Plex Media Server.',
        s159: 'Baineann logos, trádmharcanna agus trádmharcanna cláraithe eile lena n-úinéirí faoi seach.<br>Gach ceart ar cosaint.',
        s160: 'Athshocraigh go réamhshocraithe',
        // -- ... --

        s161: 'Stádas faire meáin a thosú ...',
        s162: 'Caithfidh tú do theilifís a nascadh ar an Idirlíon chun stádas gníomhachtaithe <br/> a athbhunú agus srian athsheinm a bhaint',
        s163: 'Caithfidh tú do theilifís a nascadh chuig an Idirlíon chun srian athsheinm a bhaint',
        s164: 'Tá tréimhse teoranta úsáide ag an leagan seo den iarratas. <br/> Ní féidir leat aon chomhad meáin a thuilleadh a thuilleadh. ',
        s165: 'Cruthaigh scuaine athsheinm ...',
        s166: 'Seánra anaithnid',
        s167: 'Aw, Snap! Chuaigh rud eigin mícheart',
        s168: 'Ní féidir úsáideoir roghnaithe a úsáid. <br/> Theip ar chumarsáid a dhéanamh le Plex API. ',
        s169: 'Cód PIN mícheart',
        s170: 'Iarratas ar fhaisnéis úsáideora ...',
        s171: 'Cód PIN mícheart. <br/> Féadfaidh iarrachtaí athfhriotail comhartha a dhíchumasú go sealadach i ',
        s172: 'Ní féidir faisnéis úsáideora a phróiseáil <br/> Theip ar chumarsáid a dhéanamh le Plex API',
        s173: 'Ag iarraidh ceangal le {0} ...',
        s174: 'Aw, Snap! Chuaigh rud éigin mícheart agus ní raibh muid in ann nascadh le {0} ',
        s175: 'Nasctha go rathúil le {0}',
        s176: 'Ag nascadh le {0} ...',
        s177: 'Aw, Snap! Chuaigh rud éigin mícheart agus theip ar fhíordheimhniú go {0} ',
        s178: 'Aw, Snap! Chuaigh rud éigin mícheart agus theip ar chumarsáid le {0} ',
        s179: 'Ní féidir an liosta freastalaí a fháil ó Plex API',
        s180: 'Theip ar chumarsáid a dhéanamh le Plex API',
        s181: 'Iarratas ar fhaisnéis chuntais ...',
        s182: 'Ag nascadh le plex.tv ...',
        s183: 'Iarratas ar eolas ar an bpainéal ...',
        s184: 'Aw, Snap! Chuaigh rud éigin mícheart agus níorbh fhéidir linn freagra freastalaí a phróiseáil ',
        s185: 'Baile',
        //s186: 'Leanúint ar aghaidh ag breathnú',
        s186: 'Lean ar aghaidh',
        s187: 'Le déanaí curtha leis',
        s188: 'Athraigh ó {0}',
        s189: 'Tosaigh ó thús',
        s190: 'Athsheinm a chur ar aghaidh',
        s191: 'Leantóirí',
        s192: 'Rianta fuaime',
        s193: 'Fotheidil',
        s194: 'Níos mó gníomhartha',
        s195: 'An bhfuil tú cinnte gur mhaith leat an mhír seo a scriosadh as do chóras comhaid?',
        s196: 'Scrios',
        s197: 'Íomhá meáin ó chóras comhaid a scriosadh ...',
        s198: 'Iarratas ar shonraí sna meáin ...',
        s199: 'Leantóir',
        s200: 'Meáin',
        s201: 'Aistriú',
        s202: 'Luchtú póstaer meáin ...',
        s203: 'Meáin ealaíne a luchtú ...',
        s204: 'Aw, Snap! Chuaigh rud éigin mícheart agus ní raibh muid in ann sonraí meáin a fháil ',
        s205: 'Sórtáil',
        s206: '14 póstaeir',
        s207: '33 póstaeir ',
        s208: '27 póstaeir (gan teidil) ',
        s209: '48 póstaeir (gan teidil) ',
        s210: 'Méid greille',
        s211: 'De réir Cineál',
        s212: 'De réir Ealaíontóirí',
        s213: 'Faoi Scannáin',
        s214: 'De réir Seónna Teilifíse',
        s215: 'Modh féachaint',
        s216: 'De réir Fillteáin',
        s217: 'Cruthú athuair athuair ...',
        s218: 'Iarratais ar mhíreanna leabharlainne ...',
        s219: 'Aw, Snap! Chuaigh rud éigin mícheart agus é ag cumarsáid le {0} ',
        s220: 'Iarratais ar mhíreanna leabharlainne ...',
        s221: 'Athnuachan',
        s222: 'Féach méid an ghreille',
        s223: 'Athshlánú scuaine athsheinm ...',
        s224: 'Seinn an chéad seachtain eile?',
        s225: 'Seinn',
        s226: 'Aw, Snap! Chuaigh rud éigin mícheart agus ní raibh muid in ann stádas faire meáin a dhíscaoileadh ',
        s227: 'D\'éirigh leat as an athsheinm físe',
        s228: 'Ba chúis le earráid líonra gur tharla an físe-íoslódáil go páirtaimseartha',
        s229: 'Cuireadh deireadh leis an athsheinm físe mar gheall ar fhadhb éillithe nó mar gheall ar na gnéithe físe a úsáideadh níor thacaigh do bhrabhsálaí',
        s230: 'Níorbh fhéidir an físeán a luchtú, toisc gur theip ar an bhfreastalaí nó ar an líonra nó toisc nach bhfuil an fhormáid tacaithe',
        s231: 'Tharla earráid anaithnid (cód gan sainmhíniú)',
        s232: 'Tharla earráid anaithnid',
        s233: 'Téann tréimhse taispeána in {0} lá (í)',
        s234: 'Téann tréimhse taispeána in {0}',
        s235: 'S{0}',
        s236: 'E{0}',
        s237: 'Socruithe',

        // Auto play next episode
        s238: 'Tá',

        //
        s239: 'Cuardaigh i {0}',
        s240: 'h [h] mm [min]',
        s241: 'mm [min] ss [sec]',
        s242: 'mm [min]',
        s243: 'ss [sec]'

    });