var i18n = (
    {
        s000: 'Magyar nyelvre fordította Németh Csaba', // <span style="color:#FFA500">1soproni@gmail.com</span>',
        s001: 'Újraindítás',
        s002: 'Visszajelzés és a támogatás <span style="color:#FFA500">xplay@itkey.ru</span> vagy látogasd meg a fórumot <span style="color:#FFA500">http://xplay.itkey.ru/forum/</span>',
        s003: 'A bejelentkezéshez látogasd meg ezt <span style="color:#FFA500">https://plex.tv/link</span> és írd be a kódot.',
        s004: 'Fiók linkelés újrapróbálása',
        s005: 'Elérhető szerverek listája ehhez {0}',
        s006: 'Nincs elérhető Plex Media Server',
        s007: 'Mégsem',
        s008: 'Leválasztás {0}',
        s009: 'Írd be a Plex fiók PIN kódját',
        s010: 'Lejátszás folytatása',
        s011: 'Mostanában hozzáadott',
        s012: 'Semmi megjeleníthető az irányítópulton',
        s013: 'A teszt időszak lejárt',
        s014: '{0} offline indításod maradt. Csatlakoztasd a TV-t az Internethez.',
        s015: 'Csatlakoztasd a TV-t az Internezhez az aktiváció állapotának visszaállításához',
        s016: 'Rész {0}',
        s017: 'Évad {0}',
        s018: 'Nézetlen',
        s019: '{0} rész',
        s020: 'Rendező',
        s021: 'Író',
        s022: 'Szereplők',
        s023: 'Videó',
        s024: 'Audió',
        s025: 'Feliratok',
        s026: 'Nincs',

        // -- Library (section) --

        s027: 'szűrt',
        s028: ' / ',
        s029: 'Üres könyvtár',
        s030: 'Nem található egyezés',

        // -- Filters dialog --

        s031: 'Szűrők',
        s032: 'Csak nem látottak mutatása',
        s033: 'Visszaállítás',
        s034: 'Alkalmaz',

        // -- Settings dialog --

        s035: 'Általános',
        s036: 'Videó lejátszó',
        s037: 'Zene lejátszó',
        s038: 'Fotó nézegető',
        s039: 'Irányítás',
        s040: 'Otthoni felhasználók',
        s041: 'Fiók',
        s042: 'Névjegy',
        s043: 'Általános',
        s044: 'Felület nyelve',
        s045: 'Ismeretlen',
        s046: 'Időformátum',
        s047: 'Lejátszás folytatása',
        s048: 'Audió téma',
        s049: 'Nem',
        s050: 'Igen',
        s051: 'Loop',
        s052: 'Képernyővédő',
        s053: 'Letiltva',
        s054: 'Media rating',
        s055: 'Csillagok',
        s056: 'Number',
        s057: 'Média plakátok',
        s058: 'Plakátok minősége',
        s059: 'Main media poster quality',
        s060: 'Media arts',
        s061: 'Show',
        s062: 'Show media art',
        s063: 'Minőség',
        s064: 'Media art quality',
        s065: 'Átlátszatlanság',
        s066: 'Media art opacity',
        s067: 'Blur effect',
        s068: 'Media art blur effect',
        s069: 'Playback',
        s070: 'Playback mode',
        s071: 'Következő rész indítása',

        // Auto play next episode
        s072: 'Ask',
        s073: 'Controls wake up',
        s074: 'Kurzor mozgatás',
        s075: 'Gombnyomás',
        s076: 'Kurzor vagy gomb',
        s077: 'Mozi előzetesek',
        s078: 'Gyorstekerési intervallum',
        s079: 'Controls timeout',
        s080: 'Transzkódolás',
        s081: 'Minőség',
        s082: 'Transzkódolás minősége',
        s083: 'Eredeti',
        s084: 'Audio boost',
        s085: 'Transcoding audio boost',
        s086: 'Kicsi',
        s087: 'Nagy',
        s088: 'Hatalmas',
        s089: 'Protokol',
        s090: 'Transcoding streaming protocol',
        s091: 'Direkt lejátszás',
        s092: 'Hamis',
        s093: 'Igaz',
        s094: 'Direct stream',
        s095: 'Méret',
        s096: 'Felirat mérete',
        s097: 'Apró',
        s098: 'Kicsi',
        s099: 'Normál',
        s100: 'Nagy',
        s101: 'Hatalmas',
        s102: 'Kódlap (külön felirattal)',
        s103: 'Felirat kódlapja (csak külön felirattal)',
        s104: 'Pozíció (külön felirattal)',
        s105: 'Felirat helyzete (csak külön felirattal)',
        s106: 'Szín (külön felirattal)',
        s107: 'Felirat színe (csak külön felirattal)',
        s108: 'Fehér',
        s109: 'Ezüst',
        s110: 'Szürke',
        s111: 'Fekete',
        s112: 'Lila',
        s113: 'Piros',
        s114: 'Narancs',
        s115: 'Sárga',
        s116: 'Zöld',
        s117: 'Lime',
        s118: 'Kék',
        s119: 'Világos kék',
        s120: 'Sor (mappa nézet)',
        s121: 'Sor típus (mappa nézet)',
        s122: 'Natív',
        s123: 'Local',
        s124: 'Formátum',
        s125: 'Transzkódolási formátum',
        s126: 'Bitráta',
        s127: 'Transzkódolási bitráta',
        s128: 'Autostart playback',
        s129: 'Playback timeout',
        s130: 'Loopback playback',
        s131: 'Show color background',
        s132: 'Fotó megjelenítés minősége',
        s133: 'Előző',
        s134: 'Következő',
        s135: 'Lejátszás/Szünet',
        s136: 'Megállítás',
        s137: 'Visszatekerés',
        s138: 'Továbbtekerés',
        s139: 'Gyors visszatekerés',
        s140: 'Gyors továbbtekerés',
        s141: 'Piros gomb',
        s142: 'Zöld gomb',
        s143: 'Kék gomb',
        s144: 'Sárga gomb',
        s145: 'Home users',
        s146: 'Eltávolítás',
        s147: 'Only two users can be used as local home users.<br>In case you want more home users please use native Plex Home Users feature.',
        s148: 'Beállíthatsz egy csoportot, akik együtt használják a Plex-et.<br/>Például családi felhasználók (szülők és gyerekek) akik együtt<br/>használják az ugyanahhoz a Plex Media Server-hez csatlakoztatott TV-t a házban.',
        s149: 'Csatlakozás a Plex szolgáltatásokhoz ...',
        s150: 'Plex felhasználó linkelése otthoni felhasználóhoz<br/>látogasd meg <span style="color:#FFA500">https://plex.tv/link</span> és írd be a kódot.',
        s151: 'Otthoni felhasználó hozzáadása',
        s152: 'Bejelentkezve mint',
        s153: 'Felhasználó azonosító',
        s154: 'Aktiváció állapota',
        s155: 'ISMERETLEN',
        s156: 'Plex fiók leválasztása',
        s157: 'This version of application has a limited period of usage.<br/>To remove limitation, please visit our website <span style="color:#FFA500">https://xplay.itkey.ru</span><br>and don\'t forget your user ID.',
        s158: 'Nem hivatalos kliens Plex Media Server-hez.',
        s159: 'A logók, védjegyek és egyéb bejegyzett védjegyek a tulajdonosukhoz tartoznak.<br>Minden jog fenntartva.',
        s160: 'Alapértelmezések visszaállítása',

        // -- ... --

        s161: 'Toggling media watch status ...',
        s162: 'You must connect your TV to the Internet to restore activation status <br/> and remove playback restriction',
        s163: 'You must connect your TV to the Internet to remove playback restriction',
        s164: 'This version of application has a limited period of usage. <br/> You can\'t play any media files anymore.',
        s165: 'Creating playback queue ...',
        s166: 'Ismeretlen műfaj',
        s167: 'Oh, csudába! Valami baj történt',
        s168: 'Nem lehet használni a kiválasztott felhasználót. <br/> Sikertelen kommunikáció a Plex API-val.',
        s169: 'Helytelen PIN kód',
        s170: 'Felhasználói információk lekérése ...',
        s171: 'Hibás PIN kód. <br/> Az újrapróbálkozások ideiglenesen letilthatják a belépést',
        s172: 'Felhasználói információk feldolgozása sikertelen<br/>Sikertelen kommunikáció a Plex API-val',
        s173: 'Kapcsolódási próbálkozás ide {0} ...',
        s174: 'Oh, csudába! Valami baj történt és nem lehet kapcsolódni ide {0}',
        s175: 'Sikeresen kapcsolódva ehhez {0}',
        s176: 'Kapcsolódás ide {0} ...',
        s177: 'Aw, Snap! Something went wrong and authentication to {0} failed',
        s178: 'Aw, Snap! Something went wrong and communication with {0} failed',
        s179: 'Nem tudom lekérni a szerverek listáját a Plex API-tól',
        s180: 'Sikertelen kommunikáció a Plex API-val.',
        s181: 'Fiók információk lekérése ...',
        s182: 'Kapcsolódás ide plex.tv ...',
        s183: 'Requesting dashboard information ...',
        s184: 'Oh, csudába! Valami baj történt és nem lehetett feldolgozni a szerver választás',
        s185: 'Kezdőlap',
        s186: 'Continue watching',
        s187: 'Mostanában hozzáadott',
        s188: 'Folytatás innen {0}',
        s189: 'Indítás az elejéről',
        s190: 'Lejátszás folytatása',
        s191: 'Előzetesek',
        s192: 'Audió sávok',
        s193: 'Feliratok',
        s194: 'More actions',
        s195: 'Biztosan törölni akarod ezt az elemet a fájlrendszerről?',
        s196: 'Törlés',
        s197: 'Média elem törlése a fájlrendszerről ...',
        s198: 'Média részleteinek lekérése ...',
        s199: 'Előzetes',
        s200: 'Média',
        s201: 'Transzkódolás',
        s202: 'Média plakátok töltése ...',
        s203: 'Média art töltése ...',
        s204: 'Oh, csudába! Valami baj történt és nem lehetett kinyerni a média részleteit',
        s205: 'Rendezés',
        s206: '14 plakát',
        s207: '33 plakát',
        s208: '27 plakát (címek nélkül)',
        s209: '48 plakát (címek nélkül)',
        s210: 'Rácsméret',
        s211: 'Típus szerint',
        s212: 'Művészek szerint',
        s213: 'Filmek szerint',
        s214: 'TV sorozatok szerint',
        s215: 'Nézet mód',
        s216: 'Mappák szerint',
        s217: 'Creating playback queue ...',
        s218: 'Könyvtár elemeinek lekérése ...',
        s219: 'Oh, csudába! Valami baj történt a kommunikáció közben ezzel {0}',
        s220: 'Könyvtár elemeinek lekérése ...',
        s221: 'Frissítés',
        s222: 'View grid size',
        s223: 'Lejátszási sor újraindítása ...',
        s224: 'Következő rész lejátszása?',
        s225: 'Lejátszás',
        s226: 'Aw, Snap! Something went wrong and we were unable to toggle media watch status',
        s227: 'Megszakítottad a videó lejátszását',
        s228: 'A network error caused the video download to fail part-way',
        s229: 'The video playback was aborted due to a corruption problem or because the video used features your browser did not support',
        s230: 'A videót nem lehetett betölteni szerver-, vagy hálózati hiba miatt, vagy mert a formátum nem támogatott',
        s231: 'Ismeretlen hiba történt (nem definiált kód)',
        s232: 'Ismeretlen hiba történt',
        s233: 'Demo időszak lejár {0} nap múlva',
        s234: 'Demo időszak lejár {0}',
        s235: 'É{0}',
        s236: 'R{0}',
        s237: 'Beállítások',

        // Auto play next episode
        s238: 'Igen',

        //
        s239: 'Keresés a {0}',
        s240: 'h [óra] mm [perc]',
        s241: 'mm [perc] ss [mp]',
        s242: 'mm [perc]',
        s243: 'ss [mp]',


        s244: 'Direkt',

        s245: '{0} perc',
        s246: '{0} mp'

    });
