var i18n = (
    {
        s000: 'Lingua Italiana by Red', // <span style="color:#FFA500">pirloste@hotmail.com</span>',
        s001: 'Ricomincia',
        s002: 'Email per supporto e risposte <span style="color:#FFA500">pirloste@hotmail.com</span> oppure visita il forum <span style="color:#FFA500">http://xplay.itkey.ru/forum/</span>',
        s003: 'Per accedere, visita <span style="color:#FFA500">https://plex.tv/link</span> ed inserisci il codice sopra indicato.',
        s004: 'Riprova il collegamento dell\'account',
        s005: 'Lista dei servers disponibile per {0}',
        s006: 'Nessun server Plex Media disponibile',
        s007: 'Cancella',
        s008: 'Sscollega {0}',
        s009: 'Inserisci il codice PIN del tuo account Plex',
        s010: 'Continua a guardare',
        s011: 'Aggiunti Recentemente',
        s012: 'Niente da mostrare sulla dashboard',
        s013: 'Periodo di test terminato',
        s014: 'Ti sono rimasti {0} inizi fuori linea. Per favore connetti il tuo TV ad Internet.',
        s015: 'Devi connettere il tuo TV ad Internet per ripristinare lo stato di attivazione',
        s016: 'Episodio {0}',
        s017: 'Stagione {0}',
        s018: 'Non visto',
        s019: '{0} Parti',
        s020: 'Regista',
        s021: 'Autore',
        s022: 'Cast',
        s023: 'Video',
        s024: 'Audio',
        s025: 'Sottotitoli',
        s026: 'Nessuno',

        // -- Library (section) --

        s027: 'filtro',
        s028: ' di ',
        s029: 'Libreria vuota',
        s030: 'Nessun risultato trovato',

        // -- Filters dialog --

        s031: 'Filtri',
        s032: 'Mostra solo i non visti',
        s033: 'Ripristina',
        s034: 'Applica',

        // -- Settings dialog --

        s035: 'Generale',
        s036: 'Visualizzatore Video',
        s037: 'Lettore Musicale',
        s038: 'Visualizzatore Foto',
        s039: 'Controlli',
        s040: 'Utente Home',
        s041: 'Account',
        s042: 'Di',
        s043: 'Comune',
        s044: 'Linguaggio interfaccia',
        s045: 'Sconosciuto',
        s046: 'Formato ora',
        s047: 'Continua a guardare',
        s048: 'Audio tema',
        s049: 'No',
        s050: 'Si',
        s051: 'Ciclo',
        s052: 'Salvaschermo',
        s053: 'Disabilitato',
        s054: 'Valutazione Media',
        s055: 'Stelle',
        s056: 'Numero',
        s057: 'Posters Media',
        s058: 'Qualita\' posters',
        s059: 'Qualita\' poster media principale',
        s060: 'Media arts',
        s061: 'Mostra',
        s062: 'Mostra media art',
        s063: 'Qualita\'',
        s064: 'Qualita\' Media art',
        s065: 'Opacita\'',
        s066: 'Opacita\' Media art',
        s067: 'Effetto sfocatura',
        s068: 'Effetto sfocatura Media art',
        s069: 'Riproduzione',
        s070: 'Modalita\' riproduzione',
        s071: 'Auto play prossimo episodio',

        // Auto play next episode
        s072: 'Chiedi',

        s073: 'Controlli di wake up',
        s074: 'Muovi il cursore',
        s075: 'Premi il pulsante',
        s076: 'Cursore o pulsante',
        s077: 'Cinema Trailers',
        s078: 'Cerca intervallo',
        s079: 'Controlli di timeout',
        s080: 'Trascodifica',
        s081: 'Qualita\'',
        s082: 'Qualita\' trascodifica',
        s083: 'Originale',
        s084: 'Amplificazione audio',
        s085: 'Trascodifica amplificazione audio',
        s086: 'Piccolo',
        s087: 'Medio',
        s088: 'Grande',
        s089: 'Protocollo',
        s090: 'Trascodifica il protocollo di streaming',
        s091: 'Riproduzione diretta',
        s092: 'Falso',
        s093: 'Vero',
        s094: 'Stream Diretto',
        s095: 'Grandezza',
        s096: 'Grandezza sottotitoli',
        s097: 'Minuscolo',
        s098: 'Piccolo',
        s099: 'Normale',
        s100: 'Grande',
        s101: 'Enorme',
        s102: 'Codepage (esterno)',
        s103: 'Codepage sottotitoli (solo esterni)',
        s104: 'Posizione (esterno)',
        s105: 'Posizione sottotitoli (solo esterni)',
        s106: 'Colore (esterno)',
        s107: 'Colore sottotitoli (solo esterni)',
        s108: 'Bianco',
        s109: 'Argento',
        s110: 'Grigio',
        s111: 'Nero',
        s112: 'Porpora',
        s113: 'Rosso',
        s114: 'Arancio',
        s115: 'Giallo',
        s116: 'Verde',
        s117: 'Lime',
        s118: 'Blu',
        s119: 'Blu chiaro',
        s120: 'Coda (vista per cartella)',
        s121: 'Tipo di coda (vista per cartella)',
        s122: 'Nativo',
        s123: 'Locale',
        s124: 'Formato',
        s125: 'Trascodifica formato',
        s126: 'Bitrate',
        s127: 'Trascodifica bitrate',
        s128: 'Autostart riproduzione',
        s129: 'Timeout riproduzione',
        s130: 'Loopback riproduzione',
        s131: 'Mostra colore di sfondo',
        s132: 'Qualita\' visualizzazione foto',
        s133: 'Precedent',
        s134: 'Prossimo',
        s135: 'Play/Pausa',
        s136: 'Stop',
        s137: 'Indietro',
        s138: 'Avanti',
        s139: 'Avanti veloce',
        s140: 'Indietro veloce',
        s141: 'Pulsante Rosso',
        s142: 'Pulsante Verde',
        s143: 'Pulsante Blu',
        s144: 'Pulsante Giallo',
        s145: 'Utenti Home',
        s146: 'Rimuovi',
        s147: 'Solo due utenti possono essere usati come utenti home locali.<br>In caso volessi piu\' utenti home, usa la caratteristica nativa degli utenti Home Plex.',
        s148: 'Qui puoi creare un gruppo di utenti che usano tutti insieme Plex.<br/>Per esempio, potrebbe esserci una famiglia di utenti (genitori e figli) che usano<br/>tutti Plex sul TV connesso allo stesso Plex Media Server nella loro casa.',
        s149: 'Connessione ai servizi Plex ...',
        s150: 'Per collegare un account Plex ad un utente home locale<br/>visita <span style="color:#FFA500">https://plex.tv/link</span> ed inserisci il codice sopra indicato.',
        s151: 'Aggiungi un utente home locale',
        s152: 'Collegato come',
        s153: 'ID Utente',
        s154: 'Stato attivazione',
        s155: 'SCONOSCIUTO',
        s156: 'Scollega account Plex',
        s157: 'Questa versione dell\'applicazione ha un periodo limitato di utilizzo.<br/>Per rimuovere la limitazione, visita il nostro sito <span style="color:#FFA500">https://xplay.itkey.ru</span><br>e non dimenticare il tuo ID utente.',
        s158: 'Un client non ufficiale per Plex Media Server.',
        s159: 'Loghi, marchi and altri marchi registrati appartengono ai loro rispettivi proprietari.<br>Tutti i diritti sono riservati.',
        s160: 'Ripristino iniziale',

        // -- ... --

        s161: 'Commuta lo stato di visualizzazione ...',
        s162: 'Devi collegare il tuo TV ad Internet per ripristinare lo stato di attivazione <br/> e rimuovere le restrizioni di riproduzione',
        s163: 'Devi collegare il tuo TV ad Internet per rimuovere le restrizioni di riproduzione',
        s164: 'Questa versione dell\'applicazione ha un periodo limitato di utilizzo. <br/> Non e\' possibile rirpodurre altri files.',
        s165: 'Creazione coda di riproduzione ...',
        s166: 'Genere sconosciuto',
        s167: 'Ops! Qualcosa non ha funzionato',
        s168: 'Impossibile usare l\'utente selezionato. <br/> Errore di comunicazione con la Api Plex.',
        s169: 'Codice PIN non corretto',
        s170: 'Richiesta informazioni utente ...',
        s171: 'Codice PIN non corretto. <br/> Ripetuti tentativi errati possono disattivare il sign in',
        s172: 'Impossibile processare le informazioni utente<br/>Errore di comunicazione con la Api Plex',
        s173: 'Tentativo di connessione a {0} ...',
        s174: 'Ops! Qualcosa non ha funzionato e non siamo riusciti a collegarci a {0}',
        s175: 'Collegamento riuscito a {0}',
        s176: 'Collegamento a {0} ...',
        s177: 'Ops! Qualcosa non ha funzionato nell\'autenticazione a {0}',
        s178: 'Ops! Qualcosa non ha funzionato nella comunicazione a {0}',
        s179: 'Impossibile recuperare la lista dei server dalle API Plex',
        s180: 'Errore di comunicazione con le API Plex',
        s181: 'Richiesta informazioni account ...',
        s182: 'Connessione a plex.tv ...',
        s183: 'Richiesta informazioni dashboard ...',
        s184: 'Ops! Qualcosa non ha funzionato e non siamo in grado di processare i dati del server',
        s185: 'Home',
        s186: 'Continua a guardare',
        s187: 'Aggiunti recentemente',
        s188: 'Riprendi da {0}',
        s189: 'Riprendi dall\'inizio',
        s190: 'Riprendi la riproduzione',
        s191: 'Trailers',
        s192: 'Tracce audio',
        s193: 'Sottotitoli',
        s194: 'Maggiori azioni',
        s195: 'Sei sicuro di volere cancellare questo file dal tuo sistema?',
        s196: 'Cancella',
        s197: 'Cancellazione file dal sistema ...',
        s198: 'Richiesta dettagli media ...',
        s199: 'Trailer',
        s200: 'Media',
        s201: 'Trascodifica',
        s202: 'Caricamento media poster ...',
        s203: 'Caricamento media art ...',
        s204: 'ops! Qualcosa non ha funzionato. Impossibile recuperare i dettagli del media',
        s205: 'Ordinamento',
        s206: '14 posters',
        s207: '33 posters',
        s208: '27 posters (senza titoli)',
        s209: '48 posters (senza titoli)',
        s210: 'Grandezza griglia',
        s211: 'Per Tipo',
        s212: 'Per Artista',
        s213: 'Per Film',
        s214: 'Per Programma TV',
        s215: 'Modalita\' visualizzazione',
        s216: 'Per Cartella',
        s217: 'Creazione coda riproduzione ...',
        s218: 'Richiesta elementi della libreria ...',
        s219: 'Ops! Qualcosa non ha funzionato nella comunicazione con {0}',
        s220: 'Richiesta elementi della libreria ...',
        s221: 'Aggiorna',
        s222: 'Visualizza grandezza griglia',
        s223: 'Riprendi coda di riproduzione ...',
        s224: 'Riproduco il prossimo episodio?',
        s225: 'Riproduci',
        s226: 'Ops! Qualcosa non ha funzionato. Impossibile commutare lo stato di visualizzazione del media',
        s227: 'Hai interrotto la riproduzione video',
        s228: 'Un errore di rete ha interrotto il download del video',
        s229: 'La riproduzione del video si e\' interrotta a causa del file rovinato o perche\' il video usa caratteristiche non supportate dal tuo browser',
        s230: 'Il video non puo\' essere caricato, o per un errore del server o di rete o perche\' il formato non e\' supportato',
        s231: 'Errore sconosciuto (codice sconosciuto)',
        s232: 'Errore sconosciuto',
        s233: 'Il periodo di prova termina in {0} giorno/i',
        s234: 'Il periodo di prova termina in {0}',
        s235: 'S{0}',
        s236: 'E{0}',
        s237: 'Impostazioni',

        // Auto play next episode
        s238: 'Si',

        //
        s239: 'Cerca nella {0}',
        s240: 'h [hr] mm [min]',
        s241: 'mm [min] ss [sec]',
        s242: 'mm [min]',
        s243: 'ss [sec]',


        s244: 'Diretta',

        s245: '{0} min',
        s246: '{0} sec'

    });