var i18n = (
    {
        s000: 'Nederlandse vertaling door Frans Twisk <span style="color:#FFA500">work@franstwisk.nl</span>',
        s001: 'Herstart',
        s002: 'Email voor support en feedback <span style="color:#FFA500">xplay@itkey.ru</span> of bezoek het forum <span style="color:#FFA500">http://xplay.itkey.ru/forum/</span>',
        s003: 'Om in te loggen bezoek <span style="color:#FFA500">https://plex.tv/link</span> en vul bovenstaande code in.',
        s004: 'Probeer opnieuw account te linken',
        s005: 'Lijst met beschikbare servers voor {0}',
        s006: 'Geen beschikbare Plex Media Servers',
        s007: 'Annuleer',
        s008: 'Ontkoppel {0}',
        s009: 'Voer je Plex account PIN code in',
        s010: 'Verder kijken',
        s011: 'Recent toegevoegd',
        s012: 'Niets om op het dashboard weer te geven',
        s013: 'Testperiode verlopen',
        s014: 'Je hebt {0} offline afspelen beschikbaar. Verbind je tv met internet.',
        s015: 'Je moet je tv verbinden met internet om de activeringsstatus te herstellen',
        s016: 'Aflevering {0}',
        s017: 'Seizoen {0}',
        s018: 'Onbekeken',
        s019: '{0} Delen',
        s020: 'Regisseur',
        s021: 'Schrijver',
        s022: 'Cast',
        s023: 'Video',
        s024: 'Audio',
        s025: 'Ondertiteling',
        s026: 'Geen',

        // -- Library (section) --

        s027: 'gefilterd',
        s028: ' van ',
        s029: 'Lege bibliotheek',
        s030: 'Geen resultaten gevonden',

        // -- Filters dialog --

        s031: 'filters',
        s032: 'Alleen onbekeken tonen',
        s033: 'Reset',
        s034: 'Toepassen',
        s035: 'Algemeen',
        s036: 'Video speler',
        s037: 'Muziek speler',
        s038: 'Foto speler',
        s039: 'Bediening',
        s040: 'Thuisgebruikers',
        s041: 'Account',
        s042: 'Over',
        s043: 'Algemeen',
        s044: 'Taal',
        s045: 'Onbekend',
        s046: 'Tijdnotatie',
        s047: 'Verder kijken',
        s048: 'Thema muziek',
        s049: 'Nee',
        s050: 'Ja',
        s051: 'Herhaal',
        s052: 'Screensaver',
        s053: 'Uitgeschakeld',
        s054: 'Media beoordeling',
        s055: 'Sterren',
        s056: 'Aantal',
        s057: 'Media posters',
        s058: 'Kwaliteit posters',
        s059: 'Algemene posterkwaliteit',
        s060: 'Media achtergrond',
        s061: 'Weergeven',
        s062: 'Achtergrond weergeven',
        s063: 'Kwaliteit',
        s064: 'Achtergrond kwaliteit',
        s065: 'Transparantie',
        s066: 'Achtergrond transparantie',
        s067: 'Blur effect',
        s068: 'Achtergrond blur effect',
        s069: 'Afspelen',
        s070: 'Afspeelmodus',
        s071: 'Speel volgende aflevering automatisch',
        s072: 'Vraag',
        s073: 'Ontwaak besturing',
        s074: 'Cursor verplaatsen',
        s075: 'Druk op knop',
        s076: 'Cursor of knop',
        s077: 'Bioscooptrailers',
        s078: 'Zoek interval',
        s079: 'Besturing time-out',
        s080: 'Transcoderen',
        s081: 'Kwaliteit',
        s082: 'Transcoderingskwaliteit',
        s083: 'Origineel',
        s084: 'Audio boost',
        s085: 'Transcodering audio boost',
        s086: 'Klein',
        s087: 'Groot',
        s088: 'Enorm',
        s089: 'Protocol',
        s090: 'Transcodering streaming protocol',
        s091: 'Direct spelen',
        s092: 'Aan',
        s093: 'Uit',
        s094: 'Direct stream',
        s095: 'Grootte',
        s096: 'Grootte van ondertiteling',
        s097: 'Heel klein',
        s098: 'Klein',
        s099: 'Normaal',
        s100: 'Groot',
        s101: 'Enorm',
        s102: 'Codering (extern)',
        s103: 'Codering ondertiteling (alleen extern)',
        s104: 'Positie (extern)',
        s105: 'Positie ondertiteling (alleen extern)',
        s106: 'Kleur (extern)',
        s107: 'Kleur ondertiteling (alleen extern)',
        s108: 'Wit',
        s109: 'Zilver',
        s110: 'Grijs',
        s111: 'Zwart',
        s112: 'Paars',
        s113: 'Rood',
        s114: 'Oranje',
        s115: 'Geel',
        s116: 'Groen',
        s117: 'Limoen',
        s118: 'Blauw',
        s119: 'Lichtblauw',
        s120: 'Queue (mapweergave)',
        s121: 'Queue type (mapweergave)',
        s122: 'Standaard',
        s123: 'Lokaal',
        s124: 'Formaat',
        s125: 'Formaat transcoderen',
        s126: 'Bitrate',
        s127: 'Bitrate transcoderen',
        s128: 'Automatisch afspelen',
        s129: 'Afspeel time-out',
        s130: 'Herhaal afspelen',
        s131: 'Toon achtergrondkleur',
        s132: 'Kwaliteit fotoweergave',
        s133: 'Vorige',
        s134: 'Volgende',
        s135: 'Afspelen/Pauze',
        s136: 'Stop',
        s137: 'Terugspoelen',
        s138: 'Doorspoelen',
        s139: 'Snel terugspoelen',
        s140: 'Snel doorspoelen',
        s141: 'Rode knop',
        s142: 'Groene knop',
        s143: 'Blauwe knop',
        s144: 'Gele knop',
        s145: 'Thuisgebruikers',
        s146: 'Verwijderen',
        s147: 'Er kunnen slechts twee gebruikers ingesteld worden als lokale thuisgebruiker.<br/> Indien je meer thuisgebruikers wilt, gebruik dan de officiële Plex Home Users functie.',
        s148: 'Hier kun je een groep van gebruikers instellen om Plex samen te gebruiken.<br/>Zo kun je bijvoorbeeld de hele familie (ouders en kinderen) toegang geven tot<br/>dezelfde Plex Media Server.',
        s149: 'Aan het verbinding met Plex services ...',
        s150: 'Om een Plex account te laten verbinden als lokale thuisgebruiker<br/>bezoek <span style="color:#FFA500">https://plex.tv/link</span> en voer bovenstaande code in.',
        s151: 'Voeg een lokale thuisgebruiker toe',
        s152: 'Aangemeld als',
        s153: 'Gebruikers ID',
        s154: 'Activatie status',
        s155: 'ONBEKEND',
        s156: 'Ontkoppel Plex-account',
        s157: 'Deze versie van de applicatie heeft een beperkte perdiode van gebruik. Om deze limitatie te verwijderen kun je onze website bezoeken: <span style="color:#FFA500">https://xplay.itkey.ru</span><br> en je gebruikers ID opgeven.',
        s158: 'Onofficiële client voor Plex Media Server.',
        s159: 'Logo\'s, handelsmerken en andere geregistreerde handelsmerken zijn eigendom van hun<br/>respectievelijke eigenaren.Alle rechten voorbehouden.',
        s160: 'Reset naar standaard instellingen',

        // -- ... --

        s161: 'Afspeelstatus van media wijzigen ...',
        s162: 'Je moet je tv verbinden met internet om te activeren <br/> en afspeelbeperkingen te verwijderen',
        s163: 'Je moet je tv verbinden met internet om afspeelbeperkingen te verwijderen',
        s164: 'Deze versie van de applicatie heeft een beperkte perdiode van gebruik. <br/> Je kunt momenteel niks meer afspelen.',
        s165: 'Afspeelqueue maken ...',
        s166: 'Onbekend genre',
        s167: 'Oeps! Er is iets fout gegaan',
        s168: 'Kan het huidige account niet gebruiken. <br/> Communicatie met de Plex API is mislukt.',
        s169: 'Onjuiste pincode',
        s170: 'Gebruikersinformatie opvragen ...',
        s171: 'Onjuiste pincode. <br/> Na meerdere pogingen zal inloggen tijdelijk geblokkeerd worden',
        s172: 'Kan gebruikersinformatie niet verwerken<br/>Communicatie met de Plex API is mislukt',
        s173: 'Proberen te verbinden met {0} ...',
        s174: 'Oeps! Er is iets misgegaan en we konden geen verbinding maken met {0}',
        s175: 'Succesvol verbonden met {0}',
        s176: 'Verbinden met {0} ...',
        s177: 'Oeps! Er is iets misgegaan en de verificatie naar {0} is mislukt',
        s178: 'Oeps! Er is iets misgegaan en de communicatie met {0} is mislukt',
        s179: 'Kan serverlijst niet ophalen van Plex API',
        s180: 'Communicatie met de Plex API is mislukt',
        s181: 'Accountgegevens opvragen ...',
        s182: 'Verbinden met plex.tv ...',
        s183: 'Dashboard-informatie opvragen ...',
        s184: 'Oeps! Er is iets misgegaan en we konden het antwoord van de server niet verwerken',
        s185: 'Home',
        s186: 'Verder kijken',
        s187: 'Recent toegevoegd',
        s188: 'Hervatten vanaf {0}',
        s189: 'Start vanaf het begin',
        s190: 'Hervat afspelen',
        s191: 'Trailers',
        s192: 'Audiokanalen',
        s193: 'Ondertiteling',
        s194: 'Meer acties',
        s195: 'Weet je zeker dat je dit item van je bestandssysteem wilt verwijderen?',
        s196: 'Verwijder',
        s197: 'Media-item verwijderen uit bestandssysteem ...',
        s198: 'Media details opvragen ...',
        s199: 'Trailer',
        s200: 'Media',
        s201: 'Transcodeer',
        s202: 'Media poster laden ...',
        s203: 'Media achtergrond laden ...',
        s204: 'Oh verdorie! Er is iets misgegaan en we konden geen mediadetails ophalen',
        s205: 'sorteer-',
        s206: '14 posters',
        s207: '33 posters',
        s208: '27 posters (zonder titels)',
        s209: '48 posters (zonder titels)',
        s210: 'Rastergrootte',
        s211: 'Op Type',
        s212: 'Op Artiest',
        s213: 'Op Films',
        s214: 'Op TV programma\'s',
        s215: 'Weergavemodus',
        s216: 'Op Mappen',
        s217: 'Afspeelwachtrij maken ...',
        s218: 'Bibliotheekitems aanvragen ...',
        s219: 'Oeps! Er is iets misgegaan tijdens het communiceren met {0}',
        s220: 'Bibliotheekitems aanvragen ...',
        s221: 'Verversen',
        s222: 'Bekijk rastergrootte',
        s223: 'De afspeelwachtrij opnieuw starten ...',
        s224: 'Volgende aflevering spelen?',
        s225: 'Afspelen',
        s226: 'Oeps! Er is iets misgegaan en we konden de afspeelstatus  niet wijzigen',
        s227: 'Je hebt het afspelen van de video afgebroken',
        s228: 'Door een netwerkfout is de videodownload gedeeltelijk mislukt',
        s229: 'Het afspelen van de video is afgebroken vanwege een corruptieprobleem of omdat de gebruikte video-functies niet door je browser werden ondersteund',
        s230: 'De video kon niet worden geladen, omdat de server of het netwerk faalde of omdat het formaat niet wordt ondersteund',
        s231: 'Er is een onbekende fout opgetreden (niet-gedefinieerde code)',
        s232: 'Een onbekende fout is opgetreden',
        s233: 'Demo-periode verloopt over {0} dag (en)',
        s234: 'Demo-periode verloopt over {0}',
        s235: 'S{0}',
        s236: 'A{0}',
        s237: 'Instellingen'
      });