var i18n = (
    {
        s000: 'Język polski: Jarek Krochmalski <span style="color:#FFA500">jkrochmalski@gmail.com</span>',
        s001: 'Restart',
        s002: 'Aby uzyskać wsparcie - napisz na <span style="color:#FFA500">xplay@itkey.ru</span> lub odwiedź forum <span style="color:#FFA500">http://xplay.itkey.ru/forum/</span>',
        s003: 'Aby się zalogować - odwiedź <span style="color:#FFA500">https://plex.tv/link</span> i wprowadź powyższy kod.',
        s004: 'Powtórz łączenie konta',
        s005: 'Lista dostępnych serwerów dla {0}',
        s006: 'Brak dostępnych serwerów Plex Media',
        s007: 'Anuluj',
        s008: 'Odłącz {0}',
        s009: 'Wprowadź PIN do swojego konta Plex',
        s010: 'Kontynuuj oglądanie',
        s011: 'Ostatnio dodane',
        s012: 'Brak treści do wyświetlenia',
        s013: 'Okres próbny zakończył się',
        s014: 'Pozostało {0} restartów offline. Podłącz swój telewizor do Internetu.',
        s015: 'Aby przywrócić status aktywacji, podłącz swój telewizor do Internetu',
        s016: 'Odcinek {0}',
        s017: 'Sezon {0}',
        s018: 'Nieoglądane',
        s019: '{0} części',
        s020: 'Reżyseria',
        s021: 'Scenariusz',
        s022: 'Obsada',
        s023: 'Wideo',
        s024: 'Audio',
        s025: 'Napisy',
        s026: 'Brak',

        // -- Library (section) --

        s027: 'odfiltrowano',
        s028: ' z ',
        s029: 'pusta biblioteka',
        s030: 'Nie znaleziono dopasowań',

        // -- Filters dialog --

        s031: 'Filtry',
        s032: 'Pokaż wyłącznie nieoglądane',
        s033: 'Resetuj',
        s034: 'Zastosuj',

        // -- Settings dialog --

        s035: 'Ogólne',
        s036: 'Odtwarzacz wideo',
        s037: 'Odtwarzacz muzyki',
        s038: 'Przerglądarka zdjęć',
        s039: 'Sterowanie',
        s040: 'Użytkownicy domowi',
        s041: 'Konto',
        s042: 'O programie',
        s043: 'Wspólne',
        s044: 'Język interfejsu',
        s045: 'Nieznany',
        s046: 'Format czasu',
        s047: 'Kontynuuj oglądanie',
        s048: 'Schemat audio',
        s049: 'Nie',
        s050: 'Tak',
        s051: 'Pętla',
        s052: 'Wygaszacz',
        s053: 'Wyłączony',
        s054: 'Oceny mediów',
        s055: 'Gwiazdki',
        s056: 'Liczba',
        s057: 'Plakaty mediów',
        s058: 'Jakość plakatów',
        s059: 'Jakość plakatów głównych',
        s060: 'Media',
        s061: 'Pokazuj',
        s062: 'Pokazuj grafiki',
        s063: 'Jakość',
        s064: 'Jakość grafik',
        s065: 'Przezroczystość',
        s066: 'Przezroczystość grafik',
        s067: 'Efekt rozmycia',
        s068: 'Efekt rozmycia grafik',
        s069: 'Odtwarzanie',
        s070: 'Tryb odtwarzania',
        s071: 'Automatycznie odtwarzaj następny odcinek',

        // Auto play next episode
        s072: 'Pytaj',

        s073: 'Wybudzenie sterowania',
        s074: 'Ruch kursora',
        s075: 'Naciśnięcie przycisku',
        s076: 'Kursor lub przycisk',
        s077: 'Zwiastuny kinowe',
        s078: 'Interwał',
        s079: 'Timeout sterowania',
        s080: 'Transkodowanie',
        s081: 'Jakość',
        s082: 'Jakość transkodowania',
        s083: 'Oryginalna',
        s084: 'Wzmocnienie audio',
        s085: 'Wzmocnienie audio transkodowania',
        s086: 'Małe',
        s087: 'Duże',
        s088: 'Wielkie',
        s089: 'Protokół',
        s090: 'Protokół strumieniowania przez transkodowaniu',
        s091: 'Direct play',
        s092: 'Nie',
        s093: 'Tak',
        s094: 'Strumieniowanie bezpośrednie',
        s095: 'Rozmiar',
        s096: 'Rozmiar napisów',
        s097: 'Malutkie',
        s098: 'Małe',
        s099: 'Normalne',
        s100: 'Duże',
        s101: 'Wielkie',
        s102: 'Strona kodowa (zewnętrzne)',
        s103: 'Strona kodowa napisów (tylko zewnętrzne)',
        s104: 'Pozycja (zewnętrzne)',
        s105: 'Pozycja napisów (tylko zewnętrzne)',
        s106: 'Kolor (zewnętrzne)',
        s107: 'Kolor napisów (tylko zewnętrzne)',
        s108: 'Biały',
        s109: 'Srebrny',
        s110: 'Szary',
        s111: 'Czarny',
        s112: 'Purpura',
        s113: 'Czerwony',
        s114: 'Pomarańczowy',
        s115: 'Żółty',
        s116: 'Zielony',
        s117: 'Limonkowy',
        s118: 'Niebieski',
        s119: 'Jasnoniebieski',
        s120: 'Kolejka (widok folderów)',
        s121: 'Typ kolejki (widok folderów)',
        s122: 'Natywny',
        s123: 'Lokalny',
        s124: 'Format',
        s125: 'Format transkodowania',
        s126: 'Bitrate',
        s127: 'Bitrate transkodowania',
        s128: 'Autostart odtwarzania',
        s129: 'Timeout odtwarzania',
        s130: 'Zapętlenie odtwarzania',
        s131: 'Pokazuj kolorowe tło',
        s132: 'Jakość wyświetlania zdjęć',
        s133: 'Poprzedni',
        s134: 'Następny',
        s135: 'Odtwórz/Pauza',
        s136: 'Stop',
        s137: 'Do tyłu',
        s138: 'Do przodu',
        s139: 'Szybko do tyłu',
        s140: 'Szybko do przodu',
        s141: 'Czerwony przycisk',
        s142: 'Zielony przycisk',
        s143: 'Niebieski przycisk',
        s144: 'Żółty przycisk',
        s145: 'Użytkownicy domowi',
        s146: 'Usuń',
        s147: 'Tylko dwóch użytkowników może zostać dodanych jako lokalni użytkownicy domowi.<br>Jeśli potrzebujesz większej liczby użytkowników, skorzystaj z natywnej funkcji Plex Home Users.',
        s148: 'Możesz tutaj ustawić grupę użytkowników używających wspólnie Plex'a.<br/>Przykładowo, może to być rodzina (rodzice i dzieci), którzy wspólnie<br/>korzystają z Plex'a na TV podłaczonym do tego samego serwera Plex Media w ich domu.',
        s149: 'Łączenie z usługami Plex ...',
        s150: 'Aby połączyć konto Plex jako lokalnego użytkownika domowego <br/>odwiedź <span style="color:#FFA500">https://plex.tv/link</span> i wprowadź powyższy kod.',
        s151: 'Dodaj lokalnego użytkownika domowego',
        s152: 'Zalogowano jako',
        s153: 'ID użytkownika',
        s154: 'Status aktywacji',
        s155: 'NIEZNANY',
        s156: 'Odłącz konto Plex',
        s157: 'Ta wersja aplikacji ma limitowany czas używania.<br/>Aby usunąć limit, odwiedź naszą stronę <span style="color:#FFA500">https://xplay.itkey.ru</span><br>i nie zapomnij swojego ID użytkownika.',
        s158: 'Nieoficjalny klient dla Plex Media Server.',
        s159: 'Logotypy, znaki towarowe i inne zarejestrowane znaki handlowe należą do ich odpowiednich właścicieli.<br>Wszystkie prawa zastrzeżone.',
        s160: 'Resetuj do domyślnych',

        // -- ... --

        s161: 'Przełączanie znacznika obejrzenia ...',
        s162: 'Aby przywrócić status aktywacji i usunąć restrykcje odtwarzania <br/> podłącz telewizor do Internetu.',
        s163: 'Aby przywrócić status aktywacji i usunąć restrykcje odtwarzania podłącz telewizor do Internetu',
        s164: 'Ta wersja aplikacji ma limitowany okres używania. <br/> Nie możesz więcej odwtarzać mediów.',
        s165: 'Tworzenie kolejki odtwarzania ...',
        s166: 'Nieznany rodzaj',
        s167: 'O kurczę! Coś poszło nie tak.',
        s168: 'Nie można użyć wybranego użytkownika. <br/> Błąd komunikacji z Plex API.',
        s169: 'Niepoprawny kod PIN',
        s170: 'Żądanie informacji o użytkowniku ...',
        s171: 'Niepoprawny kod PIN. <br/> Kolejne próby mogą tymczasowo zablokować logowanie',
        s172: 'Nie można przetworzyć informacji o użytkowniku<br/>Błąd komunikacji z Plex API',
        s173: 'Próba połączenia z {0} ...',
        s174: 'O kurczę! Coś poszło nie tak i nie można połączyć się z {0}',
        s175: 'Udane połączenie z {0}',
        s176: 'Łączenie z {0} ...',
        s177: 'Kurza twarz! Coś poszło nie tak i nie powiodło się uwierzytelnienie do {0}',
        s178: 'Kurza twarz! Coś poszło nie tak i komunikacja z {0} nie powiodła się',
        s179: 'Nie można pobrać listy serwerów z Plex API',
        s180: 'Nie można połączyć się z Plex API',
        s181: 'Żądanie informacji o koncie ...',
        s182: 'Łączenie z plex.tv ...',
        s183: 'Żądanie informacji o ekranie głównym ...',
        s184: 'Kurza twarz! Coś poszło nie tak i nie mogliśmy przetworzyć odpowiedzi serwera',
        s185: 'Ekran główny',
        s186: 'Kontynuuj oglądanie',
        s187: 'Ostatnio dodane',
        s188: 'Wznów od {0}',
        s189: 'Zacznij od początku',
        s190: 'Wznów odtwarzanie',
        s191: 'Zwiastuny',
        s192: 'Ścieżki audio',
        s193: 'Napisy',
        s194: 'Więcej akcji',
        s195: 'Czy na pewno usunąć tą pozycję z systemu plików?',
        s196: 'Usuń',
        s197: 'Usuwanie pozycji z systemu plików ...',
        s198: 'Żądanie informacji o multimediach ...',
        s199: 'Zwiastun',
        s200: 'Media',
        s201: 'Transkoduj',
        s202: 'Wczytywanie plakatu ...',
        s203: 'Wczytywanie grafik...',
        s204: 'Kurza twarz! Coś poszło nie tak i nie mogliśmy pobrać informacji o multimediach',
        s205: 'Sortowanie',
        s206: '14 plakatów',
        s207: '33 plakatów',
        s208: '27 plakatów (bez tytułów)',
        s209: '48 plakatów (bez tytułów)',
        s210: 'Rozmiar siatki',
        s211: 'Po typie',
        s212: 'Po wykonawcach',
        s213: 'Po filmach',
        s214: 'Po serialach',
        s215: 'Tryb widoku',
        s216: 'Po folderach',
        s217: 'Tworzenie kolejki odtwarzania ...',
        s218: 'Żądanie pozycji biblioteki ...',
        s219: 'O kurczę! Coś poszło nie tak podczas komunikacji z {0}',
        s220: 'Żądanie pozycji biblioteki ...',
        s221: 'Odśwież',
        s222: 'Rozmiar siatki',
        s223: 'Restartowanie kolejki odtwarzania ...',
        s224: 'Czy odtwarzać kolejny odcinek?',
        s225: 'Odtwarzaj',
        s226: 'Kurza twarz! Coś poszło nie tak - nie można przestawić znacznika obejrzenia',
        s227: 'Odtwarzanie wideo zostało przerwane',
        s228: 'Błąd sieci spowodował częściowe uszkodzenie pobierania wideo',
        s229: 'Odtwarzanie wideo zostało przerwane z powodu problemu z uszkodzeniem pliku lub z powodu używanych funkcji wideo, których odtwarzacz nie obsługuje',
        s230: 'Nie można załadować filmu, ponieważ serwer/sieć nie działa lub ten format nie jest obsługiwany',
        s231: 'Wystąpił nieznany błąd (nieznany kod)',
        s232: 'Wystąpił nieznany błąd',
        s233: 'Okres demo wygasa w ciągu {0} dni',
        s234: 'Okres demo wygasa w ciągu {0}',
        s235: 'S{0}',
        s236: 'E{0}',
        s237: 'Ustawienia',

        // Auto play next episode
        s238: 'Tak',

        //
        s239: 'Szukaj w {0}',
        s240: 'h [h] mm [min]',
        s241: 'mm [min] ss [sek]',
        s242: 'mm [min]',
        s243: 'ss [sek]',

        s244: 'Direct',

        s245: '{0} min',
        s246: '{0} sek'
    });
