var i18n = (
    {
        s000: 'Türkçe çeviri: kron0S <span style="color:#FFA500">futufan@outlook.com</span>',
        s001: 'Yeniden Başlat',
        s002: 'Destek ve geri bildirim için e-mail: <span style="color:#FFA500">xplay@itkey.ru</span> veya forum: <span style="color:#FFA500">http://xplay.itkey.ru/forum/</span>',
        s003: 'Giriş yapmak için <span style="color:#FFA500">https://plex.tv/link</span> adresine gidin ve TV\'deki kodu girin.',
        s004: 'Hesap bağlantısını tekrar dene',
        s005: '{0} için mevcut sunucuların listesi',
        s006: 'Kullanılabilir Plex Medya Sunucusu yok',
        s007: 'İptal',
        s008: '{0} bağlantısını kaldır',
        s009: 'Plex hesabınızın PIN kodunu girin',
        s010: 'İzlemeye devam edin',
        s011: 'Son eklenenler',
        s012: 'Gösterge tablosunda görüntülenecek bir şey yok',
        s013: 'Test süresi doldu',
        s014: '{0} çevrimdışı süreniz kaldı. Lütfen TV\'nizi internete bağlayın.',
        s015: 'Aktivasyon durumunu geri yüklemek için TV\'nizi internete bağlamanız gerekir.',
        s016: 'Bölüm {0}',
        s017: 'Sezon {0}',
        s018: 'İzlenmedi',
        s019: '{0} Parça',
        s020: 'Yönetmen',
        s021: 'Yazar',
        s022: 'Oyuncular',
        s023: 'Video',
        s024: 'Ses',
        s025: 'Altyazı',
        s026: 'Yok',

        // -- Library (section) --

        s027: 'filtreli',
        s028: '/',
        s029: 'Kütüphane boş',
        s030: 'Hiçbir eşleşme bulunamadı',

        // -- Filters dialog --

        s031: 'Filtreler',
        s032: 'Yalnızca izlemediklerimi göster',
        s033: 'Sıfırla',
        s034: 'Uygula',

        // -- Settings dialog --

        s035: 'Genel',
        s036: 'Video oynatıcı',
        s037: 'Müzik oynatıcı',
        s038: 'Fotoğraf görüntüleyici',
        s039: 'Kontroller',
        s040: 'Ev kullanıcıları',
        s041: 'Hesap',
        s042: 'Hakkında',
        s043: 'Genel',
        s044: 'Arayüz dili',
        s045: 'Bilinmeyen',
        s046: 'Saat formatı',
        s047: 'İzlemeye devam et',
        s048: 'Ses teması',
        s049: 'Hayır',
        s050: 'Evet',
        s051: 'Döngü',
        s052: 'Ekran koruyucusu',
        s053: 'Devre dışı',
        s054: 'Medya derecelendirmesi',
        s055: 'Yıldız',
        s056: 'Numara',
        s057: 'Medya posterleri',
        s058: 'Poster kalitesi',
        s059: 'Ana medya poster kalitesi',
        s060: 'Medya resimleri',
        s061: 'Göster',
        s062: 'Medya resmini göster',
        s063: 'Kalite',
        s064: 'Medya resim kalitesi',
        s065: 'Opaklık',
        s066: 'Medya resmi opaklığı',
        s067: 'Bulanıklık efekti',
        s068: 'Medya resmi bulanıklık efekti',
        s069: 'Oynatma',
        s070: 'Oynatma modu',
        s071: 'Sonraki bölümü otomatik oynat',

        // Auto play next episode
        s072: 'Sor',

        s073: 'Uyanma kontrolleri',
        s074: 'İmleç taşı',
        s075: 'Butona basın',
        s076: 'İmleç veya buton',
        s077: 'Sinema Fragmanları',
        s078: 'İleri/Geri atlama süresi',
        s079: 'Zaman aşımını kontrol et',
        s080: 'Transcoding',
        s081: 'Kalite',
        s082: 'Transcoding kalitesi',
        s083: 'Orijinal',
        s084: 'Ses yükseltici',
        s085: 'Transcoding ses yükseltmesi',
        s086: 'Küçük',
        s087: 'Büyük',
        s088: 'Çok Büyük',
        s089: 'Protokol',
        s090: 'Transcoding streaming protokolü',
        s091: 'Doğrudan oynatma',
        s092: 'Hayır',
        s093: 'Evet',
        s094: 'Doğrudan akış',
        s095: 'Boyut',
        s096: 'Altyazı boyutu',
        s097: 'Çok Küçük',
        s098: 'Küçük',
        s099: 'Normal',
        s100: 'Büyük',
        s101: 'Çok Büyük',
        s102: 'Kodlama (harici)',
        s103: 'Altyazı kodlaması (yalnızca harici)',
        s104: 'Pozisyon (harici)',
        s105: 'Altyazı pozisyonu (yalnızca harici)',
        s106: 'Renk (harici)',
        s107: 'Altyazı rengi (yalnızca harici)',
        s108: 'Beyaz',
        s109: 'Gümüş',
        s110: 'Gri',
        s111: 'Siyah',
        s112: 'Mor',
        s113: 'Kırmızı',
        s114: 'Turuncu',
        s115: 'Sarı',
        s116: 'Yeşil',
        s117: 'Misket Limonu',
        s118: 'Mavi',
        s119: 'Açık mavi',
        s120: 'Sıra (klasör görünümü)',
        s121: 'Sıra tipi (klasör görünümü)',
        s122: 'Doğal',
        s123: 'Yerel',
        s124: 'Format',
        s125: 'Transcoding format',
        s126: 'Bitrate',
        s127: 'Transcoding bitrate',
        s128: 'Oynatmayı otomatik başlatma',
        s129: 'Oynatma zaman aşımı',
        s130: 'Oynatma döngüsü',
        s131: 'Renk arka planını göster',
        s132: 'Fotoğraf görüntüleme kalitesi',
        s133: 'Önceki',
        s134: 'Sonraki',
        s135: 'Oynat/Duraklat',
        s136: 'Durdur',
        s137: 'Geri Sar',
        s138: 'İleri Sar',
        s139: 'Hızlı Geri Sar',
        s140: 'Hızlı İleri Sar',
        s141: 'Kırmızı Buton',
        s142: 'Yeşil Buton',
        s143: 'Mavi Buton',
        s144: 'Sarı Buton',
        s145: 'Ev kullanıcıları',
        s146: 'Kaldır',
        s147: 'Yerel ev kullanıcıları olarak sadece iki kullanıcı kullanılabilir.<br>Daha fazla ev kullanıcısı istemeniz durumunda lütfen yerel Plex Ev Kullanıcıları özelliğini kullanın.',
        s148: 'Burada Plex kullanan kullanıcılar için bir grup ayarlayabilirsiniz.<br/>Örneğin, tüm kullanıcılar kendi evlerinde aynı Plex Medya Sunucusuna bağlı TVde<br/>Plex kullanan bir kullanıcı ailesi (ebeveynler ve çocuklar) olabilir.',
        s149: 'Plex hizmetlerine bağlanıyor ...',
        s150: 'Bir Plex hesabına yerel ev kullanıcısı olarak bağlanmak için<br/><span style="color:#FFA500">https://plex.tv/link</span> adresini ziyaret edin ve TV\'deki kodu girin.',
        s151: 'Yerel ev kullanıcısı ekle',
        s152: 'Giriş yapıldı',
        s153: 'Kullanıcı ID',
        s154: 'Aktivasyon durumu',
        s155: 'BİLİNMEYEN',
        s156: 'Plex hesabının bağlantısını kaldır',
        s157: 'Uygulamanın bu sürümü sınırlı kullanım süresine sahiptir.<br/>Deneme süresini kaldırmak için <span style="color:#FFA500">https://xplay.itkey.ru</span> adresinde ödeme yapın<br>ve Kullanıcı ID\'nizi doğru girmeyi unutmayın.',
        s158: 'Plex Medya Sunucusu için resmi olmayan bir istemcidir.',
        s159: 'Logolar, ticari markalar ve diğer tescilli ticari markalar kendi sahiplerine aittir.<br>Tüm hakları saklıdır.',
        s160: 'Varsayılana sıfırla',

        // -- ... --

        s161: 'Medya izleme durumu değiştiriliyor ...',
        s162: 'Aktivasyon durumunu geri yüklemek ve oynatma kısıtlamasını kaldırmak için<br/>TV\'nizi internete bağlamanız gerekmektedir.',
        s163: 'Oynatma kısıtlamasını kaldırmak için TV\'nizi internete bağlamanız gerekmektedir.',
        s164: 'Uygulamanın bu sürümü sınırlı kullanım süresine sahiptir. <br/> Artık herhangi bir medya dosyasını oynatamazsınız.',
        s165: 'Oynatma kuyruğu oluşturuluyor ...',
        s166: 'Bilinmeyen tür',
        s167: 'Hata! Bir şeyler yanlış gitti',
        s168: 'Seçilen kullanıcı kullanılamıyor. <br/> Plex API ile bağlantı kurulamadı.',
        s169: 'Yanlış PIN kodu',
        s170: 'Kullanıcı bilgisi isteniyor ...',
        s171: 'Yanlış PIN kodu. <br/> Çok sayıda deneme, oturum açmayı geçici olarak devre dışı bırakabilir.',
        s172: 'Kullanıcı bilgisi işlenemedi<br/>Plex API ile iletişim kurulamadı',
        s173: '{0} bağlanmaya çalışılıyor ...',
        s174: 'Hata! Bir şeyler yanlış gitti ve {0} bağlantısı kurulamadı',
        s175: '{0} başarıyla bağlandı',
        s176: '{0} bağlanıyor ...',
        s177: 'Hata! Bir şeyler yanlış gitti ve {0} kimlik doğrulaması başarısız oldu',
        s178: 'Hata! Bir şeyler yanlış gitti ve {0} bağlantısı kurulamadı',
        s179: 'Plex API\'dan sunucu listesi alınamadı',
        s180: 'Plex API ile bağlantı kurulamadı',
        s181: 'Hesap bilgisi isteniyor ...',
        s182: 'Plex.tv bağlantısı yapılıyor ...',
        s183: 'Gösterge paneli bilgisi isteniyor ...',
        s184: 'Hata! Bir şeyler yanlış gitti ve sunucu yanıtı işlenemedi',
        s185: 'Anasayfa',
        s186: 'İzlemeye devam',
        s187: 'Son eklenenler',
        s188: '{0}\'dan devam et',
        s189: 'Baştan başla',
        s190: 'Oynatmaya devam et',
        s191: 'Fragmanlar',
        s192: 'Ses parçaları',
        s193: 'Altyazılar',
        s194: 'Daha fazla işlem',
        s195: 'Bu öğeyi dosya sisteminizden silmek istediğinizden emin misiniz?',
        s196: 'Sil',
        s197: 'Medya öğesi dosya sisteminden siliniyor ...',
        s198: 'Medya ayrıntıları isteniyor ...',
        s199: 'Fragman',
        s200: 'Medya',
        s201: 'Transcode',
        s202: 'Medya posteri yükleniyor ...',
        s203: 'Medya resmi yükleniyor ...',
        s204: 'Hata! Bir şeyler yanlış gitti ve medya ayrıntılarını alamadık',
        s205: 'Sınıflandırma',
        s206: '14 poster',
        s207: '33 poster',
        s208: '27 poster (başlık olmadan)',
        s209: '48 poster (başlık olmadan)',
        s210: 'Izgara boyutu',
        s211: 'Türe Göre',
        s212: 'Sanatçılara Göre',
        s213: 'Filmlere Göre',
        s214: 'TV Şovlarına Göre',
        s215: 'Görünüm modu',
        s216: 'Klasörlere Göre',
        s217: 'Oynatma kuyruğu oluşturuluyor ...',
        s218: 'Kütüphane öğeleri isteniyor ...',
        s219: 'Hata! Hata! {0} bağlantısı kurulurken bir şeyler yanlış gitti',
        s220: 'Kütüphane öğeleri isteniyor ...',
        s221: 'Yenile',
        s222: 'Izgara boyutu',
        s223: 'Oynatma kuyruğu yeniden başlatılıyor ...',
        s224: 'Sonraki bölümü oynat?',
        s225: 'Oynat',
        s226: 'Hata! Bir şeyler yanlış gitti ve medya izleme durumu değiştirilemedi',
        s227: 'Video oynatmayı iptal ettiniz',
        s228: 'Bir ağ hatası, video indirme işleminin kısmen başarısız olmasına neden oldu',
        s229: 'Video oynatma, bir müdahale nedeniyle veya kullanılan videoların tarayıcınız tarafından desteklenmediği için iptal edildi',
        s230: 'Sunucu, ağ başarısız olduğu için veya video formatı desteklenmediği için video yüklenemedi',
        s231: 'Bilinmeyen bir hata oluştu (tanımlanmamış kod)',
        s232: 'Bilinmeyen bir hata oluştu',
        s233: 'Deneme sürümü {0} gün içinde bitecek',
        s234: 'Deneme sürümü {0} içinde bitecek',
        s235: 'S{0}',
        s236: 'B{0}',
        s237: 'Ayarlar',

        // Auto play next episode
        s238: 'Evet',

        //
        s239: 'Ara: {0}',
        s240: 'h [sa] mm [dk]',
        s241: 'mm [dk] ss [sn]',
        s242: 'mm [dk]',
        s243: 'ss [sn]'

    });